package com.grupo6.PagamentoApp;


/**
* com/grupo6/PagamentoApp/_TransacaoStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_pagamento.idl
* Saturday, 3 October 2026 21:08:34 o'clock CAT
*/

public class _TransacaoStub extends org.omg.CORBA.portable.ObjectImpl implements com.grupo6.PagamentoApp.Transacao
{


  // Efetuar Transacao
  public boolean efetuarTransacao (com.grupo6.PagamentoApp.TransacaoDTO transacao)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("efetuarTransacao", true);
                com.grupo6.PagamentoApp.TransacaoDTOHelper.write ($out, transacao);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return efetuarTransacao (transacao        );
            } finally {
                _releaseReply ($in);
            }
  } // efetuarTransacao


  // Listar transacoes de um usuário
  public com.grupo6.PagamentoApp.TransacaoDTO[] listarTransacoes (int id_conta)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarTransacoes", true);
                $out.write_long (id_conta);
                $in = _invoke ($out);
                com.grupo6.PagamentoApp.TransacaoDTO $result[] = com.grupo6.PagamentoApp.listaTransacaoDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarTransacoes (id_conta        );
            } finally {
                _releaseReply ($in);
            }
  } // listarTransacoes

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PagamentoApp/Transacao:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _TransacaoStub
