package com.grupo6.PagamentoApp;


/**
* com/grupo6/PagamentoApp/ContaDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_pagamento.idl
* Saturday, 3 October 2026 18:26:25 o'clock CAT
*/

public final class ContaDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int id_conta = (int)0;
  public float saldo = (float)0;
  public int id_usuario = (int)0;

  public ContaDTO ()
  {
  } // ctor

  public ContaDTO (int _id_conta, float _saldo, int _id_usuario)
  {
    id_conta = _id_conta;
    saldo = _saldo;
    id_usuario = _id_usuario;
  } // ctor

} // class ContaDTO
