package com.grupo6.PagamentoApp;


/**
* com/grupo6/PagamentoApp/ContaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_pagamento.idl
* Saturday, 3 October 2026 18:26:26 o'clock CAT
*/

public interface ContaOperations 
{

  // Consultar saldo
  float consultarSaldo (int id_usuario);

  // Buscar o Id da conta
  int buscarIDConta (int id_usuario);

  // Depositar dinheiro
  boolean depositar (int id_usuario, float valor);

  // Debitar dinheiro
  boolean debitar (int id_usuario, float valor);
} // interface ContaOperations
