package com.grupo6.PagamentoApp;


/**
* com/grupo6/PagamentoApp/ContaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_pagamento.idl
* Saturday, 3 October 2026 21:08:34 o'clock CAT
*/

abstract public class ContaHelper
{
  private static String  _id = "IDL:PagamentoApp/Conta:1.0";

  public static void insert (org.omg.CORBA.Any a, com.grupo6.PagamentoApp.Conta that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.grupo6.PagamentoApp.Conta extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (com.grupo6.PagamentoApp.ContaHelper.id (), "Conta");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.grupo6.PagamentoApp.Conta read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ContaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.grupo6.PagamentoApp.Conta value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static com.grupo6.PagamentoApp.Conta narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.grupo6.PagamentoApp.Conta)
      return (com.grupo6.PagamentoApp.Conta)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.grupo6.PagamentoApp._ContaStub stub = new com.grupo6.PagamentoApp._ContaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static com.grupo6.PagamentoApp.Conta unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.grupo6.PagamentoApp.Conta)
      return (com.grupo6.PagamentoApp.Conta)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.grupo6.PagamentoApp._ContaStub stub = new com.grupo6.PagamentoApp._ContaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
