package com.grupo6.PagamentoApp;

/**
* com/grupo6/PagamentoApp/ContaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_pagamento.idl
* Friday, 2 October 2026 00:32:49 o'clock CAT
*/

public final class ContaHolder implements org.omg.CORBA.portable.Streamable
{
  public com.grupo6.PagamentoApp.Conta value = null;

  public ContaHolder ()
  {
  }

  public ContaHolder (com.grupo6.PagamentoApp.Conta initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.grupo6.PagamentoApp.ContaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.grupo6.PagamentoApp.ContaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.grupo6.PagamentoApp.ContaHelper.type ();
  }

}
