package com.grupo6.PagamentoApp;


/**
* com/grupo6/PagamentoApp/ContaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_pagamento.idl
* Saturday, 3 October 2026 21:08:34 o'clock CAT
*/

public abstract class ContaPOA extends org.omg.PortableServer.Servant
 implements com.grupo6.PagamentoApp.ContaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("criarConta", new java.lang.Integer (0));
    _methods.put ("consultarSaldo", new java.lang.Integer (1));
    _methods.put ("buscarIDConta", new java.lang.Integer (2));
    _methods.put ("depositar", new java.lang.Integer (3));
    _methods.put ("debitar", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  //Criar uma conta
       case 0:  // PagamentoApp/Conta/criarConta
       {
         com.grupo6.PagamentoApp.ContaDTO conta = com.grupo6.PagamentoApp.ContaDTOHelper.read (in);
         boolean $result = false;
         $result = this.criarConta (conta);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  // Consultar saldo
       case 1:  // PagamentoApp/Conta/consultarSaldo
       {
         int id_usuario = in.read_long ();
         float $result = (float)0;
         $result = this.consultarSaldo (id_usuario);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }


  // Buscar o Id da conta
       case 2:  // PagamentoApp/Conta/buscarIDConta
       {
         int id_usuario = in.read_long ();
         int $result = (int)0;
         $result = this.buscarIDConta (id_usuario);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }


  // Depositar dinheiro
       case 3:  // PagamentoApp/Conta/depositar
       {
         int id_usuario = in.read_long ();
         float valor = in.read_float ();
         boolean $result = false;
         $result = this.depositar (id_usuario, valor);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  // Debitar dinheiro
       case 4:  // PagamentoApp/Conta/debitar
       {
         int id_usuario = in.read_long ();
         float valor = in.read_float ();
         boolean $result = false;
         $result = this.debitar (id_usuario, valor);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PagamentoApp/Conta:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Conta _this() 
  {
    return ContaHelper.narrow(
    super._this_object());
  }

  public Conta _this(org.omg.CORBA.ORB orb) 
  {
    return ContaHelper.narrow(
    super._this_object(orb));
  }


} // class ContaPOA
