package com.grupo6.PagamentoApp;


/**
* com/grupo6/PagamentoApp/Conta.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_pagamento.idl
* Saturday, 3 October 2026 18:26:26 o'clock CAT
*/

public interface Conta extends ContaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Conta
