package com.grupo6.PagamentoApp;


/**
* com/grupo6/PagamentoApp/listaTransacaoDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_pagamento.idl
* Saturday, 3 October 2026 18:26:25 o'clock CAT
*/


//Sequencia de elementos: Sintaxe:  sequence<ParqueEstacionamento> ParqueEstacionamentoSeq;
public final class listaTransacaoDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public com.grupo6.PagamentoApp.TransacaoDTO value[] = null;

  public listaTransacaoDTOHolder ()
  {
  }

  public listaTransacaoDTOHolder (com.grupo6.PagamentoApp.TransacaoDTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.grupo6.PagamentoApp.listaTransacaoDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.grupo6.PagamentoApp.listaTransacaoDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.grupo6.PagamentoApp.listaTransacaoDTOHelper.type ();
  }

}
