package com.grupo6.PagamentoApp;


/**
* com/grupo6/PagamentoApp/TransacaoDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_pagamento.idl
* Friday, 2 October 2026 00:32:49 o'clock CAT
*/

abstract public class TransacaoDTOHelper
{
  private static String  _id = "IDL:PagamentoApp/TransacaoDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, com.grupo6.PagamentoApp.TransacaoDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.grupo6.PagamentoApp.TransacaoDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [7];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "id_transacao",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "tipo",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[2] = new org.omg.CORBA.StructMember (
            "valor",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "estado",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "data",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "hora",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[6] = new org.omg.CORBA.StructMember (
            "id_conta",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.grupo6.PagamentoApp.TransacaoDTOHelper.id (), "TransacaoDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.grupo6.PagamentoApp.TransacaoDTO read (org.omg.CORBA.portable.InputStream istream)
  {
    com.grupo6.PagamentoApp.TransacaoDTO value = new com.grupo6.PagamentoApp.TransacaoDTO ();
    value.id_transacao = istream.read_long ();
    value.tipo = istream.read_string ();
    value.valor = istream.read_float ();
    value.estado = istream.read_string ();
    value.data = istream.read_string ();
    value.hora = istream.read_string ();
    value.id_conta = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.grupo6.PagamentoApp.TransacaoDTO value)
  {
    ostream.write_long (value.id_transacao);
    ostream.write_string (value.tipo);
    ostream.write_float (value.valor);
    ostream.write_string (value.estado);
    ostream.write_string (value.data);
    ostream.write_string (value.hora);
    ostream.write_long (value.id_conta);
  }

}
