package com.grupo6.PagamentoApp;


/**
* com/grupo6/PagamentoApp/TransacaoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_pagamento.idl
* Saturday, 3 October 2026 21:08:34 o'clock CAT
*/

public abstract class TransacaoPOA extends org.omg.PortableServer.Servant
 implements com.grupo6.PagamentoApp.TransacaoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("efetuarTransacao", new java.lang.Integer (0));
    _methods.put ("listarTransacoes", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Efetuar Transacao
       case 0:  // PagamentoApp/Transacao/efetuarTransacao
       {
         com.grupo6.PagamentoApp.TransacaoDTO transacao = com.grupo6.PagamentoApp.TransacaoDTOHelper.read (in);
         boolean $result = false;
         $result = this.efetuarTransacao (transacao);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  // Listar transacoes de um usuário
       case 1:  // PagamentoApp/Transacao/listarTransacoes
       {
         int id_conta = in.read_long ();
         com.grupo6.PagamentoApp.TransacaoDTO $result[] = null;
         $result = this.listarTransacoes (id_conta);
         out = $rh.createReply();
         com.grupo6.PagamentoApp.listaTransacaoDTOHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PagamentoApp/Transacao:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Transacao _this() 
  {
    return TransacaoHelper.narrow(
    super._this_object());
  }

  public Transacao _this(org.omg.CORBA.ORB orb) 
  {
    return TransacaoHelper.narrow(
    super._this_object(orb));
  }


} // class TransacaoPOA
