package com.grupo6.PagamentoApp;


/**
* com/grupo6/PagamentoApp/Transacao.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_pagamento.idl
* Friday, 2 October 2026 00:32:49 o'clock CAT
*/

public interface Transacao extends TransacaoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Transacao
