package com.grupo6.PagamentoApp;

/**
* com/grupo6/PagamentoApp/TransacaoDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_pagamento.idl
* Friday, 2 October 2026 00:32:49 o'clock CAT
*/

public final class TransacaoDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public com.grupo6.PagamentoApp.TransacaoDTO value = null;

  public TransacaoDTOHolder ()
  {
  }

  public TransacaoDTOHolder (com.grupo6.PagamentoApp.TransacaoDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.grupo6.PagamentoApp.TransacaoDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.grupo6.PagamentoApp.TransacaoDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.grupo6.PagamentoApp.TransacaoDTOHelper.type ();
  }

}
