package com.grupo6.PagamentoApp;


/**
* com/grupo6/PagamentoApp/TransacaoDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_pagamento.idl
* Friday, 2 October 2026 00:32:49 o'clock CAT
*/

public final class TransacaoDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int id_transacao = (int)0;
  public String tipo = null;
  public float valor = (float)0;
  public String estado = null;
  public String data = null;
  public String hora = null;
  public int id_conta = (int)0;

  public TransacaoDTO ()
  {
  } // ctor

  public TransacaoDTO (int _id_transacao, String _tipo, float _valor, String _estado, String _data, String _hora, int _id_conta)
  {
    id_transacao = _id_transacao;
    tipo = _tipo;
    valor = _valor;
    estado = _estado;
    data = _data;
    hora = _hora;
    id_conta = _id_conta;
  } // ctor

} // class TransacaoDTO
