package com.grupo6.PagamentoApp;


/**
* com/grupo6/PagamentoApp/TransacaoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_pagamento.idl
* Friday, 2 October 2026 00:32:49 o'clock CAT
*/

public interface TransacaoOperations 
{

  // Efetuar Transacao
  boolean EfetuarTransacao (com.grupo6.PagamentoApp.TransacaoDTO transacao);

  // Listar transacoes de um usuário
  com.grupo6.PagamentoApp.TransacaoDTO[] listarTransacoes (int id_conta);
} // interface TransacaoOperations
