# Python stubs generated by omniidl from ../idl/sistema_pagamento.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "PagamentoApp"
#
__name__ = "PagamentoApp"
_0_PagamentoApp = omniORB.openModule("PagamentoApp", r"../idl/sistema_pagamento.idl")
_0_PagamentoApp__POA = omniORB.openModule("PagamentoApp__POA", r"../idl/sistema_pagamento.idl")


# struct TransacaoDTO
_0_PagamentoApp.TransacaoDTO = omniORB.newEmptyClass()
class TransacaoDTO (omniORB.StructBase):
    _NP_RepositoryId = "IDL:PagamentoApp/TransacaoDTO:1.0"

    def __init__(self, id_transacao, tipo, valor, estado, data, hora, id_conta):
        self.id_transacao = id_transacao
        self.tipo = tipo
        self.valor = valor
        self.estado = estado
        self.data = data
        self.hora = hora
        self.id_conta = id_conta

_0_PagamentoApp.TransacaoDTO = TransacaoDTO
_0_PagamentoApp._d_TransacaoDTO  = (omniORB.tcInternal.tv_struct, TransacaoDTO, TransacaoDTO._NP_RepositoryId, "TransacaoDTO", "id_transacao", omniORB.tcInternal.tv_long, "tipo", (omniORB.tcInternal.tv_string,0), "valor", omniORB.tcInternal.tv_float, "estado", (omniORB.tcInternal.tv_string,0), "data", (omniORB.tcInternal.tv_string,0), "hora", (omniORB.tcInternal.tv_string,0), "id_conta", omniORB.tcInternal.tv_long)
_0_PagamentoApp._tc_TransacaoDTO = omniORB.tcInternal.createTypeCode(_0_PagamentoApp._d_TransacaoDTO)
omniORB.registerType(TransacaoDTO._NP_RepositoryId, _0_PagamentoApp._d_TransacaoDTO, _0_PagamentoApp._tc_TransacaoDTO)
del TransacaoDTO

# struct ContaDTO
_0_PagamentoApp.ContaDTO = omniORB.newEmptyClass()
class ContaDTO (omniORB.StructBase):
    _NP_RepositoryId = "IDL:PagamentoApp/ContaDTO:1.0"

    def __init__(self, id_conta, saldo, id_usuario):
        self.id_conta = id_conta
        self.saldo = saldo
        self.id_usuario = id_usuario

_0_PagamentoApp.ContaDTO = ContaDTO
_0_PagamentoApp._d_ContaDTO  = (omniORB.tcInternal.tv_struct, ContaDTO, ContaDTO._NP_RepositoryId, "ContaDTO", "id_conta", omniORB.tcInternal.tv_long, "saldo", omniORB.tcInternal.tv_float, "id_usuario", omniORB.tcInternal.tv_long)
_0_PagamentoApp._tc_ContaDTO = omniORB.tcInternal.createTypeCode(_0_PagamentoApp._d_ContaDTO)
omniORB.registerType(ContaDTO._NP_RepositoryId, _0_PagamentoApp._d_ContaDTO, _0_PagamentoApp._tc_ContaDTO)
del ContaDTO

# typedef ... listaTransacaoDTO
class listaTransacaoDTO:
    _NP_RepositoryId = "IDL:PagamentoApp/listaTransacaoDTO:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_PagamentoApp.listaTransacaoDTO = listaTransacaoDTO
_0_PagamentoApp._d_listaTransacaoDTO  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:PagamentoApp/TransacaoDTO:1.0"], 0)
_0_PagamentoApp._ad_listaTransacaoDTO = (omniORB.tcInternal.tv_alias, listaTransacaoDTO._NP_RepositoryId, "listaTransacaoDTO", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:PagamentoApp/TransacaoDTO:1.0"], 0))
_0_PagamentoApp._tc_listaTransacaoDTO = omniORB.tcInternal.createTypeCode(_0_PagamentoApp._ad_listaTransacaoDTO)
omniORB.registerType(listaTransacaoDTO._NP_RepositoryId, _0_PagamentoApp._ad_listaTransacaoDTO, _0_PagamentoApp._tc_listaTransacaoDTO)
del listaTransacaoDTO

# interface Conta
_0_PagamentoApp._d_Conta = (omniORB.tcInternal.tv_objref, "IDL:PagamentoApp/Conta:1.0", "Conta")
omniORB.typeMapping["IDL:PagamentoApp/Conta:1.0"] = _0_PagamentoApp._d_Conta
_0_PagamentoApp.Conta = omniORB.newEmptyClass()
class Conta :
    _NP_RepositoryId = _0_PagamentoApp._d_Conta[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_PagamentoApp.Conta = Conta
_0_PagamentoApp._tc_Conta = omniORB.tcInternal.createTypeCode(_0_PagamentoApp._d_Conta)
omniORB.registerType(Conta._NP_RepositoryId, _0_PagamentoApp._d_Conta, _0_PagamentoApp._tc_Conta)

# Conta operations and attributes
Conta._d_consultarSaldo = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_float, ), None)
Conta._d_buscarIDConta = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_long, ), None)
Conta._d_depositar = ((omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_float), (omniORB.tcInternal.tv_boolean, ), None)
Conta._d_debitar = ((omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_float), (omniORB.tcInternal.tv_boolean, ), None)

# Conta object reference
class _objref_Conta (CORBA.Object):
    _NP_RepositoryId = Conta._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def consultarSaldo(self, *args):
        return self._obj.invoke("consultarSaldo", _0_PagamentoApp.Conta._d_consultarSaldo, args)

    def buscarIDConta(self, *args):
        return self._obj.invoke("buscarIDConta", _0_PagamentoApp.Conta._d_buscarIDConta, args)

    def depositar(self, *args):
        return self._obj.invoke("depositar", _0_PagamentoApp.Conta._d_depositar, args)

    def debitar(self, *args):
        return self._obj.invoke("debitar", _0_PagamentoApp.Conta._d_debitar, args)

omniORB.registerObjref(Conta._NP_RepositoryId, _objref_Conta)
_0_PagamentoApp._objref_Conta = _objref_Conta
del Conta, _objref_Conta

# Conta skeleton
__name__ = "PagamentoApp__POA"
class Conta (PortableServer.Servant):
    _NP_RepositoryId = _0_PagamentoApp.Conta._NP_RepositoryId


    _omni_op_d = {"consultarSaldo": _0_PagamentoApp.Conta._d_consultarSaldo, "buscarIDConta": _0_PagamentoApp.Conta._d_buscarIDConta, "depositar": _0_PagamentoApp.Conta._d_depositar, "debitar": _0_PagamentoApp.Conta._d_debitar}

Conta._omni_skeleton = Conta
_0_PagamentoApp__POA.Conta = Conta
omniORB.registerSkeleton(Conta._NP_RepositoryId, Conta)
del Conta
__name__ = "PagamentoApp"

# interface Transacao
_0_PagamentoApp._d_Transacao = (omniORB.tcInternal.tv_objref, "IDL:PagamentoApp/Transacao:1.0", "Transacao")
omniORB.typeMapping["IDL:PagamentoApp/Transacao:1.0"] = _0_PagamentoApp._d_Transacao
_0_PagamentoApp.Transacao = omniORB.newEmptyClass()
class Transacao :
    _NP_RepositoryId = _0_PagamentoApp._d_Transacao[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_PagamentoApp.Transacao = Transacao
_0_PagamentoApp._tc_Transacao = omniORB.tcInternal.createTypeCode(_0_PagamentoApp._d_Transacao)
omniORB.registerType(Transacao._NP_RepositoryId, _0_PagamentoApp._d_Transacao, _0_PagamentoApp._tc_Transacao)

# Transacao operations and attributes
Transacao._d_efetuarTransacao = ((omniORB.typeMapping["IDL:PagamentoApp/TransacaoDTO:1.0"], ), (omniORB.tcInternal.tv_boolean, ), None)
Transacao._d_listarTransacoes = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:PagamentoApp/listaTransacaoDTO:1.0"], ), None)

# Transacao object reference
class _objref_Transacao (CORBA.Object):
    _NP_RepositoryId = Transacao._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def efetuarTransacao(self, *args):
        return self._obj.invoke("efetuarTransacao", _0_PagamentoApp.Transacao._d_efetuarTransacao, args)

    def listarTransacoes(self, *args):
        return self._obj.invoke("listarTransacoes", _0_PagamentoApp.Transacao._d_listarTransacoes, args)

omniORB.registerObjref(Transacao._NP_RepositoryId, _objref_Transacao)
_0_PagamentoApp._objref_Transacao = _objref_Transacao
del Transacao, _objref_Transacao

# Transacao skeleton
__name__ = "PagamentoApp__POA"
class Transacao (PortableServer.Servant):
    _NP_RepositoryId = _0_PagamentoApp.Transacao._NP_RepositoryId


    _omni_op_d = {"efetuarTransacao": _0_PagamentoApp.Transacao._d_efetuarTransacao, "listarTransacoes": _0_PagamentoApp.Transacao._d_listarTransacoes}

Transacao._omni_skeleton = Transacao
_0_PagamentoApp__POA.Transacao = Transacao
omniORB.registerSkeleton(Transacao._NP_RepositoryId, Transacao)
del Transacao
__name__ = "PagamentoApp"

#
# End of module "PagamentoApp"
#
__name__ = "sistema_pagamento_idl"

_exported_modules = ( "PagamentoApp", )

# The end.
