# Python stubs generated by omniidl from ../idl/sistema_parqueamento.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "ParqueamentoApp"
#
__name__ = "ParqueamentoApp"
_0_ParqueamentoApp = omniORB.openModule("ParqueamentoApp", r"../idl/sistema_parqueamento.idl")
_0_ParqueamentoApp__POA = omniORB.openModule("ParqueamentoApp__POA", r"../idl/sistema_parqueamento.idl")


# struct UsuarioDTO
_0_ParqueamentoApp.UsuarioDTO = omniORB.newEmptyClass()
class UsuarioDTO (omniORB.StructBase):
    _NP_RepositoryId = "IDL:ParqueamentoApp/UsuarioDTO:1.0"

    def __init__(self, id_usuario, nome, telefone, senha, tipo):
        self.id_usuario = id_usuario
        self.nome = nome
        self.telefone = telefone
        self.senha = senha
        self.tipo = tipo

_0_ParqueamentoApp.UsuarioDTO = UsuarioDTO
_0_ParqueamentoApp._d_UsuarioDTO  = (omniORB.tcInternal.tv_struct, UsuarioDTO, UsuarioDTO._NP_RepositoryId, "UsuarioDTO", "id_usuario", omniORB.tcInternal.tv_long, "nome", (omniORB.tcInternal.tv_string,0), "telefone", (omniORB.tcInternal.tv_string,0), "senha", (omniORB.tcInternal.tv_string,0), "tipo", omniORB.tcInternal.tv_long)
_0_ParqueamentoApp._tc_UsuarioDTO = omniORB.tcInternal.createTypeCode(_0_ParqueamentoApp._d_UsuarioDTO)
omniORB.registerType(UsuarioDTO._NP_RepositoryId, _0_ParqueamentoApp._d_UsuarioDTO, _0_ParqueamentoApp._tc_UsuarioDTO)
del UsuarioDTO

# struct ParqueDTO
_0_ParqueamentoApp.ParqueDTO = omniORB.newEmptyClass()
class ParqueDTO (omniORB.StructBase):
    _NP_RepositoryId = "IDL:ParqueamentoApp/ParqueDTO:1.0"

    def __init__(self, id_parque, nome, provincia, localizacao, telefone, horario, cobertura, preco, foto_url):
        self.id_parque = id_parque
        self.nome = nome
        self.provincia = provincia
        self.localizacao = localizacao
        self.telefone = telefone
        self.horario = horario
        self.cobertura = cobertura
        self.preco = preco
        self.foto_url = foto_url

_0_ParqueamentoApp.ParqueDTO = ParqueDTO
_0_ParqueamentoApp._d_ParqueDTO  = (omniORB.tcInternal.tv_struct, ParqueDTO, ParqueDTO._NP_RepositoryId, "ParqueDTO", "id_parque", omniORB.tcInternal.tv_long, "nome", (omniORB.tcInternal.tv_string,0), "provincia", (omniORB.tcInternal.tv_string,0), "localizacao", (omniORB.tcInternal.tv_string,0), "telefone", (omniORB.tcInternal.tv_string,0), "horario", (omniORB.tcInternal.tv_string,0), "cobertura", (omniORB.tcInternal.tv_string,0), "preco", omniORB.tcInternal.tv_float, "foto_url", (omniORB.tcInternal.tv_string,0))
_0_ParqueamentoApp._tc_ParqueDTO = omniORB.tcInternal.createTypeCode(_0_ParqueamentoApp._d_ParqueDTO)
omniORB.registerType(ParqueDTO._NP_RepositoryId, _0_ParqueamentoApp._d_ParqueDTO, _0_ParqueamentoApp._tc_ParqueDTO)
del ParqueDTO

# struct VagaDTO
_0_ParqueamentoApp.VagaDTO = omniORB.newEmptyClass()
class VagaDTO (omniORB.StructBase):
    _NP_RepositoryId = "IDL:ParqueamentoApp/VagaDTO:1.0"

    def __init__(self, id_vaga, numero_vaga, estado, id_parque):
        self.id_vaga = id_vaga
        self.numero_vaga = numero_vaga
        self.estado = estado
        self.id_parque = id_parque

_0_ParqueamentoApp.VagaDTO = VagaDTO
_0_ParqueamentoApp._d_VagaDTO  = (omniORB.tcInternal.tv_struct, VagaDTO, VagaDTO._NP_RepositoryId, "VagaDTO", "id_vaga", omniORB.tcInternal.tv_long, "numero_vaga", (omniORB.tcInternal.tv_string,0), "estado", omniORB.tcInternal.tv_long, "id_parque", omniORB.tcInternal.tv_long)
_0_ParqueamentoApp._tc_VagaDTO = omniORB.tcInternal.createTypeCode(_0_ParqueamentoApp._d_VagaDTO)
omniORB.registerType(VagaDTO._NP_RepositoryId, _0_ParqueamentoApp._d_VagaDTO, _0_ParqueamentoApp._tc_VagaDTO)
del VagaDTO

# struct ViaturaDTO
_0_ParqueamentoApp.ViaturaDTO = omniORB.newEmptyClass()
class ViaturaDTO (omniORB.StructBase):
    _NP_RepositoryId = "IDL:ParqueamentoApp/ViaturaDTO:1.0"

    def __init__(self, id_viatura, marca, modelo, matricula, id_usuario):
        self.id_viatura = id_viatura
        self.marca = marca
        self.modelo = modelo
        self.matricula = matricula
        self.id_usuario = id_usuario

_0_ParqueamentoApp.ViaturaDTO = ViaturaDTO
_0_ParqueamentoApp._d_ViaturaDTO  = (omniORB.tcInternal.tv_struct, ViaturaDTO, ViaturaDTO._NP_RepositoryId, "ViaturaDTO", "id_viatura", omniORB.tcInternal.tv_long, "marca", (omniORB.tcInternal.tv_string,0), "modelo", (omniORB.tcInternal.tv_string,0), "matricula", (omniORB.tcInternal.tv_string,0), "id_usuario", omniORB.tcInternal.tv_long)
_0_ParqueamentoApp._tc_ViaturaDTO = omniORB.tcInternal.createTypeCode(_0_ParqueamentoApp._d_ViaturaDTO)
omniORB.registerType(ViaturaDTO._NP_RepositoryId, _0_ParqueamentoApp._d_ViaturaDTO, _0_ParqueamentoApp._tc_ViaturaDTO)
del ViaturaDTO

# struct ReservaDTO
_0_ParqueamentoApp.ReservaDTO = omniORB.newEmptyClass()
class ReservaDTO (omniORB.StructBase):
    _NP_RepositoryId = "IDL:ParqueamentoApp/ReservaDTO:1.0"

    def __init__(self, id_reserva, data_entrada, hora_entrada, data_saida, hora_saida, preco_total, id_vaga, id_usuario, id_viatura):
        self.id_reserva = id_reserva
        self.data_entrada = data_entrada
        self.hora_entrada = hora_entrada
        self.data_saida = data_saida
        self.hora_saida = hora_saida
        self.preco_total = preco_total
        self.id_vaga = id_vaga
        self.id_usuario = id_usuario
        self.id_viatura = id_viatura

_0_ParqueamentoApp.ReservaDTO = ReservaDTO
_0_ParqueamentoApp._d_ReservaDTO  = (omniORB.tcInternal.tv_struct, ReservaDTO, ReservaDTO._NP_RepositoryId, "ReservaDTO", "id_reserva", omniORB.tcInternal.tv_long, "data_entrada", (omniORB.tcInternal.tv_string,0), "hora_entrada", (omniORB.tcInternal.tv_string,0), "data_saida", (omniORB.tcInternal.tv_string,0), "hora_saida", (omniORB.tcInternal.tv_string,0), "preco_total", omniORB.tcInternal.tv_float, "id_vaga", omniORB.tcInternal.tv_long, "id_usuario", omniORB.tcInternal.tv_long, "id_viatura", omniORB.tcInternal.tv_long)
_0_ParqueamentoApp._tc_ReservaDTO = omniORB.tcInternal.createTypeCode(_0_ParqueamentoApp._d_ReservaDTO)
omniORB.registerType(ReservaDTO._NP_RepositoryId, _0_ParqueamentoApp._d_ReservaDTO, _0_ParqueamentoApp._tc_ReservaDTO)
del ReservaDTO

# typedef ... listaParqueDTO
class listaParqueDTO:
    _NP_RepositoryId = "IDL:ParqueamentoApp/listaParqueDTO:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_ParqueamentoApp.listaParqueDTO = listaParqueDTO
_0_ParqueamentoApp._d_listaParqueDTO  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ParqueamentoApp/ParqueDTO:1.0"], 0)
_0_ParqueamentoApp._ad_listaParqueDTO = (omniORB.tcInternal.tv_alias, listaParqueDTO._NP_RepositoryId, "listaParqueDTO", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ParqueamentoApp/ParqueDTO:1.0"], 0))
_0_ParqueamentoApp._tc_listaParqueDTO = omniORB.tcInternal.createTypeCode(_0_ParqueamentoApp._ad_listaParqueDTO)
omniORB.registerType(listaParqueDTO._NP_RepositoryId, _0_ParqueamentoApp._ad_listaParqueDTO, _0_ParqueamentoApp._tc_listaParqueDTO)
del listaParqueDTO

# typedef ... listaVagaDTO
class listaVagaDTO:
    _NP_RepositoryId = "IDL:ParqueamentoApp/listaVagaDTO:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_ParqueamentoApp.listaVagaDTO = listaVagaDTO
_0_ParqueamentoApp._d_listaVagaDTO  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ParqueamentoApp/VagaDTO:1.0"], 0)
_0_ParqueamentoApp._ad_listaVagaDTO = (omniORB.tcInternal.tv_alias, listaVagaDTO._NP_RepositoryId, "listaVagaDTO", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ParqueamentoApp/VagaDTO:1.0"], 0))
_0_ParqueamentoApp._tc_listaVagaDTO = omniORB.tcInternal.createTypeCode(_0_ParqueamentoApp._ad_listaVagaDTO)
omniORB.registerType(listaVagaDTO._NP_RepositoryId, _0_ParqueamentoApp._ad_listaVagaDTO, _0_ParqueamentoApp._tc_listaVagaDTO)
del listaVagaDTO

# typedef ... listaViaturaDTO
class listaViaturaDTO:
    _NP_RepositoryId = "IDL:ParqueamentoApp/listaViaturaDTO:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_ParqueamentoApp.listaViaturaDTO = listaViaturaDTO
_0_ParqueamentoApp._d_listaViaturaDTO  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ParqueamentoApp/ViaturaDTO:1.0"], 0)
_0_ParqueamentoApp._ad_listaViaturaDTO = (omniORB.tcInternal.tv_alias, listaViaturaDTO._NP_RepositoryId, "listaViaturaDTO", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ParqueamentoApp/ViaturaDTO:1.0"], 0))
_0_ParqueamentoApp._tc_listaViaturaDTO = omniORB.tcInternal.createTypeCode(_0_ParqueamentoApp._ad_listaViaturaDTO)
omniORB.registerType(listaViaturaDTO._NP_RepositoryId, _0_ParqueamentoApp._ad_listaViaturaDTO, _0_ParqueamentoApp._tc_listaViaturaDTO)
del listaViaturaDTO

# typedef ... listaReservaDTO
class listaReservaDTO:
    _NP_RepositoryId = "IDL:ParqueamentoApp/listaReservaDTO:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_ParqueamentoApp.listaReservaDTO = listaReservaDTO
_0_ParqueamentoApp._d_listaReservaDTO  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ParqueamentoApp/ReservaDTO:1.0"], 0)
_0_ParqueamentoApp._ad_listaReservaDTO = (omniORB.tcInternal.tv_alias, listaReservaDTO._NP_RepositoryId, "listaReservaDTO", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ParqueamentoApp/ReservaDTO:1.0"], 0))
_0_ParqueamentoApp._tc_listaReservaDTO = omniORB.tcInternal.createTypeCode(_0_ParqueamentoApp._ad_listaReservaDTO)
omniORB.registerType(listaReservaDTO._NP_RepositoryId, _0_ParqueamentoApp._ad_listaReservaDTO, _0_ParqueamentoApp._tc_listaReservaDTO)
del listaReservaDTO

# interface Usuario
_0_ParqueamentoApp._d_Usuario = (omniORB.tcInternal.tv_objref, "IDL:ParqueamentoApp/Usuario:1.0", "Usuario")
omniORB.typeMapping["IDL:ParqueamentoApp/Usuario:1.0"] = _0_ParqueamentoApp._d_Usuario
_0_ParqueamentoApp.Usuario = omniORB.newEmptyClass()
class Usuario :
    _NP_RepositoryId = _0_ParqueamentoApp._d_Usuario[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_ParqueamentoApp.Usuario = Usuario
_0_ParqueamentoApp._tc_Usuario = omniORB.tcInternal.createTypeCode(_0_ParqueamentoApp._d_Usuario)
omniORB.registerType(Usuario._NP_RepositoryId, _0_ParqueamentoApp._d_Usuario, _0_ParqueamentoApp._tc_Usuario)

# Usuario operations and attributes
Usuario._d_login = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.typeMapping["IDL:ParqueamentoApp/UsuarioDTO:1.0"], ), None)
Usuario._d_cadastrar = ((omniORB.typeMapping["IDL:ParqueamentoApp/UsuarioDTO:1.0"], ), (), None)
Usuario._d_actualizarDados = ((omniORB.typeMapping["IDL:ParqueamentoApp/UsuarioDTO:1.0"], ), (omniORB.tcInternal.tv_boolean, ), None)

# Usuario object reference
class _objref_Usuario (CORBA.Object):
    _NP_RepositoryId = Usuario._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def login(self, *args):
        return self._obj.invoke("login", _0_ParqueamentoApp.Usuario._d_login, args)

    def cadastrar(self, *args):
        return self._obj.invoke("cadastrar", _0_ParqueamentoApp.Usuario._d_cadastrar, args)

    def actualizarDados(self, *args):
        return self._obj.invoke("actualizarDados", _0_ParqueamentoApp.Usuario._d_actualizarDados, args)

omniORB.registerObjref(Usuario._NP_RepositoryId, _objref_Usuario)
_0_ParqueamentoApp._objref_Usuario = _objref_Usuario
del Usuario, _objref_Usuario

# Usuario skeleton
__name__ = "ParqueamentoApp__POA"
class Usuario (PortableServer.Servant):
    _NP_RepositoryId = _0_ParqueamentoApp.Usuario._NP_RepositoryId


    _omni_op_d = {"login": _0_ParqueamentoApp.Usuario._d_login, "cadastrar": _0_ParqueamentoApp.Usuario._d_cadastrar, "actualizarDados": _0_ParqueamentoApp.Usuario._d_actualizarDados}

Usuario._omni_skeleton = Usuario
_0_ParqueamentoApp__POA.Usuario = Usuario
omniORB.registerSkeleton(Usuario._NP_RepositoryId, Usuario)
del Usuario
__name__ = "ParqueamentoApp"

# interface Parque
_0_ParqueamentoApp._d_Parque = (omniORB.tcInternal.tv_objref, "IDL:ParqueamentoApp/Parque:1.0", "Parque")
omniORB.typeMapping["IDL:ParqueamentoApp/Parque:1.0"] = _0_ParqueamentoApp._d_Parque
_0_ParqueamentoApp.Parque = omniORB.newEmptyClass()
class Parque :
    _NP_RepositoryId = _0_ParqueamentoApp._d_Parque[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_ParqueamentoApp.Parque = Parque
_0_ParqueamentoApp._tc_Parque = omniORB.tcInternal.createTypeCode(_0_ParqueamentoApp._d_Parque)
omniORB.registerType(Parque._NP_RepositoryId, _0_ParqueamentoApp._d_Parque, _0_ParqueamentoApp._tc_Parque)

# Parque operations and attributes
Parque._d_adicionarParque = ((omniORB.typeMapping["IDL:ParqueamentoApp/ParqueDTO:1.0"], ), (), None)
Parque._d_editarParque = ((omniORB.typeMapping["IDL:ParqueamentoApp/ParqueDTO:1.0"], ), (omniORB.tcInternal.tv_boolean, ), None)
Parque._d_removerParque = ((omniORB.tcInternal.tv_long, ), (), None)
Parque._d_pesquisarPorCategoria = (((omniORB.tcInternal.tv_string,0), ), (omniORB.typeMapping["IDL:ParqueamentoApp/listaParqueDTO:1.0"], ), None)

# Parque object reference
class _objref_Parque (CORBA.Object):
    _NP_RepositoryId = Parque._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def adicionarParque(self, *args):
        return self._obj.invoke("adicionarParque", _0_ParqueamentoApp.Parque._d_adicionarParque, args)

    def editarParque(self, *args):
        return self._obj.invoke("editarParque", _0_ParqueamentoApp.Parque._d_editarParque, args)

    def removerParque(self, *args):
        return self._obj.invoke("removerParque", _0_ParqueamentoApp.Parque._d_removerParque, args)

    def pesquisarPorCategoria(self, *args):
        return self._obj.invoke("pesquisarPorCategoria", _0_ParqueamentoApp.Parque._d_pesquisarPorCategoria, args)

omniORB.registerObjref(Parque._NP_RepositoryId, _objref_Parque)
_0_ParqueamentoApp._objref_Parque = _objref_Parque
del Parque, _objref_Parque

# Parque skeleton
__name__ = "ParqueamentoApp__POA"
class Parque (PortableServer.Servant):
    _NP_RepositoryId = _0_ParqueamentoApp.Parque._NP_RepositoryId


    _omni_op_d = {"adicionarParque": _0_ParqueamentoApp.Parque._d_adicionarParque, "editarParque": _0_ParqueamentoApp.Parque._d_editarParque, "removerParque": _0_ParqueamentoApp.Parque._d_removerParque, "pesquisarPorCategoria": _0_ParqueamentoApp.Parque._d_pesquisarPorCategoria}

Parque._omni_skeleton = Parque
_0_ParqueamentoApp__POA.Parque = Parque
omniORB.registerSkeleton(Parque._NP_RepositoryId, Parque)
del Parque
__name__ = "ParqueamentoApp"

# interface Vaga
_0_ParqueamentoApp._d_Vaga = (omniORB.tcInternal.tv_objref, "IDL:ParqueamentoApp/Vaga:1.0", "Vaga")
omniORB.typeMapping["IDL:ParqueamentoApp/Vaga:1.0"] = _0_ParqueamentoApp._d_Vaga
_0_ParqueamentoApp.Vaga = omniORB.newEmptyClass()
class Vaga :
    _NP_RepositoryId = _0_ParqueamentoApp._d_Vaga[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_ParqueamentoApp.Vaga = Vaga
_0_ParqueamentoApp._tc_Vaga = omniORB.tcInternal.createTypeCode(_0_ParqueamentoApp._d_Vaga)
omniORB.registerType(Vaga._NP_RepositoryId, _0_ParqueamentoApp._d_Vaga, _0_ParqueamentoApp._tc_Vaga)

# Vaga operations and attributes
Vaga._d_adicionarVaga = ((omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long), (), None)
Vaga._d_actualizarEstadoVaga = ((omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long), (omniORB.tcInternal.tv_boolean, ), None)
Vaga._d_listarVagas = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:ParqueamentoApp/listaVagaDTO:1.0"], ), None)
Vaga._d_numeroTotalVagas = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_long, ), None)
Vaga._d_listarVagasDisponiveis = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:ParqueamentoApp/listaVagaDTO:1.0"], ), None)

# Vaga object reference
class _objref_Vaga (CORBA.Object):
    _NP_RepositoryId = Vaga._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def adicionarVaga(self, *args):
        return self._obj.invoke("adicionarVaga", _0_ParqueamentoApp.Vaga._d_adicionarVaga, args)

    def actualizarEstadoVaga(self, *args):
        return self._obj.invoke("actualizarEstadoVaga", _0_ParqueamentoApp.Vaga._d_actualizarEstadoVaga, args)

    def listarVagas(self, *args):
        return self._obj.invoke("listarVagas", _0_ParqueamentoApp.Vaga._d_listarVagas, args)

    def numeroTotalVagas(self, *args):
        return self._obj.invoke("numeroTotalVagas", _0_ParqueamentoApp.Vaga._d_numeroTotalVagas, args)

    def listarVagasDisponiveis(self, *args):
        return self._obj.invoke("listarVagasDisponiveis", _0_ParqueamentoApp.Vaga._d_listarVagasDisponiveis, args)

omniORB.registerObjref(Vaga._NP_RepositoryId, _objref_Vaga)
_0_ParqueamentoApp._objref_Vaga = _objref_Vaga
del Vaga, _objref_Vaga

# Vaga skeleton
__name__ = "ParqueamentoApp__POA"
class Vaga (PortableServer.Servant):
    _NP_RepositoryId = _0_ParqueamentoApp.Vaga._NP_RepositoryId


    _omni_op_d = {"adicionarVaga": _0_ParqueamentoApp.Vaga._d_adicionarVaga, "actualizarEstadoVaga": _0_ParqueamentoApp.Vaga._d_actualizarEstadoVaga, "listarVagas": _0_ParqueamentoApp.Vaga._d_listarVagas, "numeroTotalVagas": _0_ParqueamentoApp.Vaga._d_numeroTotalVagas, "listarVagasDisponiveis": _0_ParqueamentoApp.Vaga._d_listarVagasDisponiveis}

Vaga._omni_skeleton = Vaga
_0_ParqueamentoApp__POA.Vaga = Vaga
omniORB.registerSkeleton(Vaga._NP_RepositoryId, Vaga)
del Vaga
__name__ = "ParqueamentoApp"

# interface Viatura
_0_ParqueamentoApp._d_Viatura = (omniORB.tcInternal.tv_objref, "IDL:ParqueamentoApp/Viatura:1.0", "Viatura")
omniORB.typeMapping["IDL:ParqueamentoApp/Viatura:1.0"] = _0_ParqueamentoApp._d_Viatura
_0_ParqueamentoApp.Viatura = omniORB.newEmptyClass()
class Viatura :
    _NP_RepositoryId = _0_ParqueamentoApp._d_Viatura[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_ParqueamentoApp.Viatura = Viatura
_0_ParqueamentoApp._tc_Viatura = omniORB.tcInternal.createTypeCode(_0_ParqueamentoApp._d_Viatura)
omniORB.registerType(Viatura._NP_RepositoryId, _0_ParqueamentoApp._d_Viatura, _0_ParqueamentoApp._tc_Viatura)

# Viatura operations and attributes
Viatura._d_adicionarViatura = ((omniORB.typeMapping["IDL:ParqueamentoApp/ViaturaDTO:1.0"], ), (), None)
Viatura._d_listarViaturas = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:ParqueamentoApp/listaViaturaDTO:1.0"], ), None)
Viatura._d_removerViatura = ((omniORB.tcInternal.tv_long, ), (), None)

# Viatura object reference
class _objref_Viatura (CORBA.Object):
    _NP_RepositoryId = Viatura._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def adicionarViatura(self, *args):
        return self._obj.invoke("adicionarViatura", _0_ParqueamentoApp.Viatura._d_adicionarViatura, args)

    def listarViaturas(self, *args):
        return self._obj.invoke("listarViaturas", _0_ParqueamentoApp.Viatura._d_listarViaturas, args)

    def removerViatura(self, *args):
        return self._obj.invoke("removerViatura", _0_ParqueamentoApp.Viatura._d_removerViatura, args)

omniORB.registerObjref(Viatura._NP_RepositoryId, _objref_Viatura)
_0_ParqueamentoApp._objref_Viatura = _objref_Viatura
del Viatura, _objref_Viatura

# Viatura skeleton
__name__ = "ParqueamentoApp__POA"
class Viatura (PortableServer.Servant):
    _NP_RepositoryId = _0_ParqueamentoApp.Viatura._NP_RepositoryId


    _omni_op_d = {"adicionarViatura": _0_ParqueamentoApp.Viatura._d_adicionarViatura, "listarViaturas": _0_ParqueamentoApp.Viatura._d_listarViaturas, "removerViatura": _0_ParqueamentoApp.Viatura._d_removerViatura}

Viatura._omni_skeleton = Viatura
_0_ParqueamentoApp__POA.Viatura = Viatura
omniORB.registerSkeleton(Viatura._NP_RepositoryId, Viatura)
del Viatura
__name__ = "ParqueamentoApp"

# interface Reserva
_0_ParqueamentoApp._d_Reserva = (omniORB.tcInternal.tv_objref, "IDL:ParqueamentoApp/Reserva:1.0", "Reserva")
omniORB.typeMapping["IDL:ParqueamentoApp/Reserva:1.0"] = _0_ParqueamentoApp._d_Reserva
_0_ParqueamentoApp.Reserva = omniORB.newEmptyClass()
class Reserva :
    _NP_RepositoryId = _0_ParqueamentoApp._d_Reserva[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_ParqueamentoApp.Reserva = Reserva
_0_ParqueamentoApp._tc_Reserva = omniORB.tcInternal.createTypeCode(_0_ParqueamentoApp._d_Reserva)
omniORB.registerType(Reserva._NP_RepositoryId, _0_ParqueamentoApp._d_Reserva, _0_ParqueamentoApp._tc_Reserva)

# Reserva operations and attributes
Reserva._d_criarReserva = ((omniORB.typeMapping["IDL:ParqueamentoApp/ReservaDTO:1.0"], ), (omniORB.tcInternal.tv_boolean, ), None)
Reserva._d_obterReserva = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:ParqueamentoApp/ReservaDTO:1.0"], ), None)
Reserva._d_listarReservas = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:ParqueamentoApp/listaReservaDTO:1.0"], ), None)

# Reserva object reference
class _objref_Reserva (CORBA.Object):
    _NP_RepositoryId = Reserva._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def criarReserva(self, *args):
        return self._obj.invoke("criarReserva", _0_ParqueamentoApp.Reserva._d_criarReserva, args)

    def obterReserva(self, *args):
        return self._obj.invoke("obterReserva", _0_ParqueamentoApp.Reserva._d_obterReserva, args)

    def listarReservas(self, *args):
        return self._obj.invoke("listarReservas", _0_ParqueamentoApp.Reserva._d_listarReservas, args)

omniORB.registerObjref(Reserva._NP_RepositoryId, _objref_Reserva)
_0_ParqueamentoApp._objref_Reserva = _objref_Reserva
del Reserva, _objref_Reserva

# Reserva skeleton
__name__ = "ParqueamentoApp__POA"
class Reserva (PortableServer.Servant):
    _NP_RepositoryId = _0_ParqueamentoApp.Reserva._NP_RepositoryId


    _omni_op_d = {"criarReserva": _0_ParqueamentoApp.Reserva._d_criarReserva, "obterReserva": _0_ParqueamentoApp.Reserva._d_obterReserva, "listarReservas": _0_ParqueamentoApp.Reserva._d_listarReservas}

Reserva._omni_skeleton = Reserva
_0_ParqueamentoApp__POA.Reserva = Reserva
omniORB.registerSkeleton(Reserva._NP_RepositoryId, Reserva)
del Reserva
__name__ = "ParqueamentoApp"

#
# End of module "ParqueamentoApp"
#
__name__ = "sistema_parqueamento_idl"

_exported_modules = ( "ParqueamentoApp", )

# The end.
