package com.grupo6.ParqueamentoApp.VagaPackage;


/**
* com/grupo6/ParqueamentoApp/VagaPackage/listaDeVagasHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Sunday, 27 September 2026 17:57:19 o'clock CAT
*/

public final class listaDeVagasHolder implements org.omg.CORBA.portable.Streamable
{
  public com.grupo6.ParqueamentoApp.Vaga value[] = null;

  public listaDeVagasHolder ()
  {
  }

  public listaDeVagasHolder (com.grupo6.ParqueamentoApp.Vaga[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.grupo6.ParqueamentoApp.VagaPackage.listaDeVagasHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.grupo6.ParqueamentoApp.VagaPackage.listaDeVagasHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.grupo6.ParqueamentoApp.VagaPackage.listaDeVagasHelper.type ();
  }

}
