# DO NOT EDIT THIS FILE!
#
# Python module ParqueamentoApp generated by omniidl

import omniORB
omniORB.updateModule("ParqueamentoApp")

# ** 1. Stub files contributing to this module
import sistema_parqueamento_idl

# ** 2. Sub-modules

# ** 3. End
