package com.grupo6.ParqueamentoApp.ViaturaPackage;


/**
* com/grupo6/ParqueamentoApp/ViaturaPackage/listaDeViaturasHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Sunday, 27 September 2026 17:57:20 o'clock CAT
*/


// ==========================
public final class listaDeViaturasHolder implements org.omg.CORBA.portable.Streamable
{
  public com.grupo6.ParqueamentoApp.Viatura value[] = null;

  public listaDeViaturasHolder ()
  {
  }

  public listaDeViaturasHolder (com.grupo6.ParqueamentoApp.Viatura[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.grupo6.ParqueamentoApp.ViaturaPackage.listaDeViaturasHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.grupo6.ParqueamentoApp.ViaturaPackage.listaDeViaturasHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.grupo6.ParqueamentoApp.ViaturaPackage.listaDeViaturasHelper.type ();
  }

}
