# DO NOT EDIT THIS FILE!
#
# Python module ParqueamentoApp__POA generated by omniidl

import omniORB
omniORB.updateModule("ParqueamentoApp__POA")

# ** 1. Stub files contributing to this module
import sistema_parqueamento_idl

# ** 2. Sub-modules

# ** 3. End
