package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/_ParqueStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Monday, 28 September 2026 20:31:17 o'clock CAT
*/

public class _ParqueStub extends org.omg.CORBA.portable.ObjectImpl implements com.grupo6.ParqueamentoApp.Parque
{


  // ==========================
  public void adicionarParque (String nome, String provincia, String localizacao, String telefone, String horario, String cobertura, float precoHora, String fotoUrl)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("adicionarParque", true);
                $out.write_string (nome);
                $out.write_string (provincia);
                $out.write_string (localizacao);
                $out.write_string (telefone);
                $out.write_string (horario);
                $out.write_string (cobertura);
                $out.write_float (precoHora);
                $out.write_string (fotoUrl);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                adicionarParque (nome, provincia, localizacao, telefone, horario, cobertura, precoHora, fotoUrl        );
            } finally {
                _releaseReply ($in);
            }
  } // adicionarParque

  public void editarParque (int id_parque, String nome, String provincia, String localizacao, String telefone, String horario, String cobertura, float precoHora, String fotoUrl)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("editarParque", true);
                $out.write_long (id_parque);
                $out.write_string (nome);
                $out.write_string (provincia);
                $out.write_string (localizacao);
                $out.write_string (telefone);
                $out.write_string (horario);
                $out.write_string (cobertura);
                $out.write_float (precoHora);
                $out.write_string (fotoUrl);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                editarParque (id_parque, nome, provincia, localizacao, telefone, horario, cobertura, precoHora, fotoUrl        );
            } finally {
                _releaseReply ($in);
            }
  } // editarParque

  public void removerParque (int id_parque)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("removerParque", true);
                $out.write_long (id_parque);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                removerParque (id_parque        );
            } finally {
                _releaseReply ($in);
            }
  } // removerParque

  public com.grupo6.ParqueamentoApp.ParqueDTO[] pesquisarPorCategoria (String categoria)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("pesquisarPorCategoria", true);
                $out.write_string (categoria);
                $in = _invoke ($out);
                com.grupo6.ParqueamentoApp.ParqueDTO $result[] = com.grupo6.ParqueamentoApp.listaParqueDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return pesquisarPorCategoria (categoria        );
            } finally {
                _releaseReply ($in);
            }
  } // pesquisarPorCategoria

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ParqueamentoApp/Parque:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ParqueStub
