package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/_ReservaStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Monday, 28 September 2026 20:31:17 o'clock CAT
*/

public class _ReservaStub extends org.omg.CORBA.portable.ObjectImpl implements com.grupo6.ParqueamentoApp.Reserva
{


  // ==========================
  public void criarReserva (String data_entrada, String hora_entrada, String data_saida, String hora_saida, int id_vaga, int id_usuario, int id_viatura)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("criarReserva", true);
                $out.write_string (data_entrada);
                $out.write_string (hora_entrada);
                $out.write_string (data_saida);
                $out.write_string (hora_saida);
                $out.write_long (id_vaga);
                $out.write_long (id_usuario);
                $out.write_long (id_viatura);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                criarReserva (data_entrada, hora_entrada, data_saida, hora_saida, id_vaga, id_usuario, id_viatura        );
            } finally {
                _releaseReply ($in);
            }
  } // criarReserva

  public com.grupo6.ParqueamentoApp.ReservaDTO obterReserva (int id_reserva)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("obterReserva", true);
                $out.write_long (id_reserva);
                $in = _invoke ($out);
                com.grupo6.ParqueamentoApp.ReservaDTO $result = com.grupo6.ParqueamentoApp.ReservaDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return obterReserva (id_reserva        );
            } finally {
                _releaseReply ($in);
            }
  } // obterReserva

  public com.grupo6.ParqueamentoApp.ReservaDTO[] listarReservas (int id_usuario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarReservas", true);
                $out.write_long (id_usuario);
                $in = _invoke ($out);
                com.grupo6.ParqueamentoApp.ReservaDTO $result[] = com.grupo6.ParqueamentoApp.listaReservaDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarReservas (id_usuario        );
            } finally {
                _releaseReply ($in);
            }
  } // listarReservas

  public void cancelarReserva (int id_reserva)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("cancelarReserva", true);
                $out.write_long (id_reserva);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                cancelarReserva (id_reserva        );
            } finally {
                _releaseReply ($in);
            }
  } // cancelarReserva

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ParqueamentoApp/Reserva:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ReservaStub
