package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/_SistemaParqueamentoStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 21:45:54 o'clock CAT
*/

public class _SistemaParqueamentoStub extends org.omg.CORBA.portable.ObjectImpl implements com.grupo6.ParqueamentoApp.SistemaParqueamento
{


  // ==========================
  public com.grupo6.ParqueamentoApp.Usuario login (String nome, String senha) throws com.grupo6.ParqueamentoApp.UsuarioNaoEncontrado
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("login", true);
                $out.write_string (nome);
                $out.write_string (senha);
                $in = _invoke ($out);
                com.grupo6.ParqueamentoApp.Usuario $result = com.grupo6.ParqueamentoApp.UsuarioHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:ParqueamentoApp/UsuarioNaoEncontrado:1.0"))
                    throw com.grupo6.ParqueamentoApp.UsuarioNaoEncontradoHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return login (nome, senha        );
            } finally {
                _releaseReply ($in);
            }
  } // login


  // ==========================
  public com.grupo6.ParqueamentoApp.ParqueEstacionamento[] listarParques ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarParques", true);
                $in = _invoke ($out);
                com.grupo6.ParqueamentoApp.ParqueEstacionamento $result[] = com.grupo6.ParqueamentoApp.ParqueEstacionamentoSeqHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarParques (        );
            } finally {
                _releaseReply ($in);
            }
  } // listarParques

  public com.grupo6.ParqueamentoApp.ParqueEstacionamento[] pesquisarPorProvincia (String provincia)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("pesquisarPorProvincia", true);
                $out.write_string (provincia);
                $in = _invoke ($out);
                com.grupo6.ParqueamentoApp.ParqueEstacionamento $result[] = com.grupo6.ParqueamentoApp.ParqueEstacionamentoSeqHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return pesquisarPorProvincia (provincia        );
            } finally {
                _releaseReply ($in);
            }
  } // pesquisarPorProvincia

  public com.grupo6.ParqueamentoApp.ParqueEstacionamento[] pesquisarPorNome (String nome)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("pesquisarPorNome", true);
                $out.write_string (nome);
                $in = _invoke ($out);
                com.grupo6.ParqueamentoApp.ParqueEstacionamento $result[] = com.grupo6.ParqueamentoApp.ParqueEstacionamentoSeqHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return pesquisarPorNome (nome        );
            } finally {
                _releaseReply ($in);
            }
  } // pesquisarPorNome

  public com.grupo6.ParqueamentoApp.ParqueEstacionamento[] pesquisarPorPreco (double precoMaximo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("pesquisarPorPreco", true);
                $out.write_double (precoMaximo);
                $in = _invoke ($out);
                com.grupo6.ParqueamentoApp.ParqueEstacionamento $result[] = com.grupo6.ParqueamentoApp.ParqueEstacionamentoSeqHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return pesquisarPorPreco (precoMaximo        );
            } finally {
                _releaseReply ($in);
            }
  } // pesquisarPorPreco

  public void adicionarParque (com.grupo6.ParqueamentoApp.ParqueEstacionamento parque) throws com.grupo6.ParqueamentoApp.OperacaoInvalida
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("adicionarParque", true);
                com.grupo6.ParqueamentoApp.ParqueEstacionamentoHelper.write ($out, parque);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:ParqueamentoApp/OperacaoInvalida:1.0"))
                    throw com.grupo6.ParqueamentoApp.OperacaoInvalidaHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                adicionarParque (parque        );
            } finally {
                _releaseReply ($in);
            }
  } // adicionarParque

  public void editarParque (com.grupo6.ParqueamentoApp.ParqueEstacionamento parque) throws com.grupo6.ParqueamentoApp.ParqueNaoEncontrado, com.grupo6.ParqueamentoApp.OperacaoInvalida
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("editarParque", true);
                com.grupo6.ParqueamentoApp.ParqueEstacionamentoHelper.write ($out, parque);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:ParqueamentoApp/ParqueNaoEncontrado:1.0"))
                    throw com.grupo6.ParqueamentoApp.ParqueNaoEncontradoHelper.read ($in);
                else if (_id.equals ("IDL:ParqueamentoApp/OperacaoInvalida:1.0"))
                    throw com.grupo6.ParqueamentoApp.OperacaoInvalidaHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                editarParque (parque        );
            } finally {
                _releaseReply ($in);
            }
  } // editarParque

  public void removerParque (int id_parque) throws com.grupo6.ParqueamentoApp.ParqueNaoEncontrado
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("removerParque", true);
                $out.write_long (id_parque);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:ParqueamentoApp/ParqueNaoEncontrado:1.0"))
                    throw com.grupo6.ParqueamentoApp.ParqueNaoEncontradoHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                removerParque (id_parque        );
            } finally {
                _releaseReply ($in);
            }
  } // removerParque


  // ==========================
  public com.grupo6.ParqueamentoApp.VagaEstacionamento[] listarVagas (int id_parque)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarVagas", true);
                $out.write_long (id_parque);
                $in = _invoke ($out);
                com.grupo6.ParqueamentoApp.VagaEstacionamento $result[] = com.grupo6.ParqueamentoApp.VagaEstacionamentoSeqHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarVagas (id_parque        );
            } finally {
                _releaseReply ($in);
            }
  } // listarVagas

  public com.grupo6.ParqueamentoApp.VagaEstacionamento[] listarVagasDisponiveis (int id_parque)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarVagasDisponiveis", true);
                $out.write_long (id_parque);
                $in = _invoke ($out);
                com.grupo6.ParqueamentoApp.VagaEstacionamento $result[] = com.grupo6.ParqueamentoApp.VagaEstacionamentoSeqHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarVagasDisponiveis (id_parque        );
            } finally {
                _releaseReply ($in);
            }
  } // listarVagasDisponiveis


  // ==========================
  public com.grupo6.ParqueamentoApp.Viatura adicionarViatura (String marca, String modelo, String matricula, int id_usuario) throws com.grupo6.ParqueamentoApp.UsuarioNaoEncontrado, com.grupo6.ParqueamentoApp.OperacaoInvalida
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("adicionarViatura", true);
                $out.write_string (marca);
                $out.write_string (modelo);
                $out.write_string (matricula);
                $out.write_long (id_usuario);
                $in = _invoke ($out);
                com.grupo6.ParqueamentoApp.Viatura $result = com.grupo6.ParqueamentoApp.ViaturaHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:ParqueamentoApp/UsuarioNaoEncontrado:1.0"))
                    throw com.grupo6.ParqueamentoApp.UsuarioNaoEncontradoHelper.read ($in);
                else if (_id.equals ("IDL:ParqueamentoApp/OperacaoInvalida:1.0"))
                    throw com.grupo6.ParqueamentoApp.OperacaoInvalidaHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return adicionarViatura (marca, modelo, matricula, id_usuario        );
            } finally {
                _releaseReply ($in);
            }
  } // adicionarViatura

  public com.grupo6.ParqueamentoApp.Viatura[] listarViaturas (int id_usuario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarViaturas", true);
                $out.write_long (id_usuario);
                $in = _invoke ($out);
                com.grupo6.ParqueamentoApp.Viatura $result[] = com.grupo6.ParqueamentoApp.ViaturaSeqHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarViaturas (id_usuario        );
            } finally {
                _releaseReply ($in);
            }
  } // listarViaturas

  public void removerViatura (int id_viatura) throws com.grupo6.ParqueamentoApp.ViaturaNaoEncontrada
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("removerViatura", true);
                $out.write_long (id_viatura);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:ParqueamentoApp/ViaturaNaoEncontrada:1.0"))
                    throw com.grupo6.ParqueamentoApp.ViaturaNaoEncontradaHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                removerViatura (id_viatura        );
            } finally {
                _releaseReply ($in);
            }
  } // removerViatura


  // ==========================
  public com.grupo6.ParqueamentoApp.Reserva criarReserva (String dataEntrada, String horaEntrada, String dataSaida, String horaSaida, float preco_total, int idVaga, int idUsuario, int idViatura) throws com.grupo6.ParqueamentoApp.UsuarioNaoEncontrado, com.grupo6.ParqueamentoApp.VagaNaoEncontrada, com.grupo6.ParqueamentoApp.ViaturaNaoEncontrada, com.grupo6.ParqueamentoApp.VagaOcupada, com.grupo6.ParqueamentoApp.OperacaoInvalida
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("criarReserva", true);
                $out.write_string (dataEntrada);
                $out.write_string (horaEntrada);
                $out.write_string (dataSaida);
                $out.write_string (horaSaida);
                $out.write_float (preco_total);
                $out.write_long (idVaga);
                $out.write_long (idUsuario);
                $out.write_long (idViatura);
                $in = _invoke ($out);
                com.grupo6.ParqueamentoApp.Reserva $result = com.grupo6.ParqueamentoApp.ReservaHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:ParqueamentoApp/UsuarioNaoEncontrado:1.0"))
                    throw com.grupo6.ParqueamentoApp.UsuarioNaoEncontradoHelper.read ($in);
                else if (_id.equals ("IDL:ParqueamentoApp/VagaNaoEncontrada:1.0"))
                    throw com.grupo6.ParqueamentoApp.VagaNaoEncontradaHelper.read ($in);
                else if (_id.equals ("IDL:ParqueamentoApp/ViaturaNaoEncontrada:1.0"))
                    throw com.grupo6.ParqueamentoApp.ViaturaNaoEncontradaHelper.read ($in);
                else if (_id.equals ("IDL:ParqueamentoApp/VagaOcupada:1.0"))
                    throw com.grupo6.ParqueamentoApp.VagaOcupadaHelper.read ($in);
                else if (_id.equals ("IDL:ParqueamentoApp/OperacaoInvalida:1.0"))
                    throw com.grupo6.ParqueamentoApp.OperacaoInvalidaHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return criarReserva (dataEntrada, horaEntrada, dataSaida, horaSaida, preco_total, idVaga, idUsuario, idViatura        );
            } finally {
                _releaseReply ($in);
            }
  } // criarReserva

  public com.grupo6.ParqueamentoApp.Reserva obterReserva (int idReserva) throws com.grupo6.ParqueamentoApp.ReservaNaoEncontrada
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("obterReserva", true);
                $out.write_long (idReserva);
                $in = _invoke ($out);
                com.grupo6.ParqueamentoApp.Reserva $result = com.grupo6.ParqueamentoApp.ReservaHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:ParqueamentoApp/ReservaNaoEncontrada:1.0"))
                    throw com.grupo6.ParqueamentoApp.ReservaNaoEncontradaHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return obterReserva (idReserva        );
            } finally {
                _releaseReply ($in);
            }
  } // obterReserva

  public com.grupo6.ParqueamentoApp.Reserva[] listarReservas (int idUsuario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarReservas", true);
                $out.write_long (idUsuario);
                $in = _invoke ($out);
                com.grupo6.ParqueamentoApp.Reserva $result[] = com.grupo6.ParqueamentoApp.ReservaSeqHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarReservas (idUsuario        );
            } finally {
                _releaseReply ($in);
            }
  } // listarReservas

  public void cancelarReserva (int idReserva) throws com.grupo6.ParqueamentoApp.ReservaNaoEncontrada, com.grupo6.ParqueamentoApp.OperacaoInvalida
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("cancelarReserva", true);
                $out.write_long (idReserva);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:ParqueamentoApp/ReservaNaoEncontrada:1.0"))
                    throw com.grupo6.ParqueamentoApp.ReservaNaoEncontradaHelper.read ($in);
                else if (_id.equals ("IDL:ParqueamentoApp/OperacaoInvalida:1.0"))
                    throw com.grupo6.ParqueamentoApp.OperacaoInvalidaHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                cancelarReserva (idReserva        );
            } finally {
                _releaseReply ($in);
            }
  } // cancelarReserva

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ParqueamentoApp/SistemaParqueamento:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _SistemaParqueamentoStub
