package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/_UsuarioStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Monday, 28 September 2026 20:31:17 o'clock CAT
*/


//Interfaces
public class _UsuarioStub extends org.omg.CORBA.portable.ObjectImpl implements com.grupo6.ParqueamentoApp.Usuario
{


  // ==========================
  public com.grupo6.ParqueamentoApp.UsuarioDTO login (String telefone, String senha)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("login", true);
                $out.write_string (telefone);
                $out.write_string (senha);
                $in = _invoke ($out);
                com.grupo6.ParqueamentoApp.UsuarioDTO $result = com.grupo6.ParqueamentoApp.UsuarioDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return login (telefone, senha        );
            } finally {
                _releaseReply ($in);
            }
  } // login

  public void cadastrar (String nome, String telefone, String senha, int tipo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("cadastrar", true);
                $out.write_string (nome);
                $out.write_string (telefone);
                $out.write_string (senha);
                $out.write_long (tipo);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                cadastrar (nome, telefone, senha, tipo        );
            } finally {
                _releaseReply ($in);
            }
  } // cadastrar

  public com.grupo6.ParqueamentoApp.UsuarioDTO actualizarDados (int id_usuario, String nome, String telefone, String senha)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("actualizarDados", true);
                $out.write_long (id_usuario);
                $out.write_string (nome);
                $out.write_string (telefone);
                $out.write_string (senha);
                $in = _invoke ($out);
                com.grupo6.ParqueamentoApp.UsuarioDTO $result = com.grupo6.ParqueamentoApp.UsuarioDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return actualizarDados (id_usuario, nome, telefone, senha        );
            } finally {
                _releaseReply ($in);
            }
  } // actualizarDados

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ParqueamentoApp/Usuario:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _UsuarioStub
