package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/_VagaStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Tuesday, 6 October 2026 19:06:14 o'clock CAT
*/

public class _VagaStub extends org.omg.CORBA.portable.ObjectImpl implements com.grupo6.ParqueamentoApp.Vaga
{


  // ==========================
  public void adicionarVaga (int id_parque, int numero_de_vagas)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("adicionarVaga", true);
                $out.write_long (id_parque);
                $out.write_long (numero_de_vagas);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                adicionarVaga (id_parque, numero_de_vagas        );
            } finally {
                _releaseReply ($in);
            }
  } // adicionarVaga

  public boolean actualizarEstadoVaga (int id_vaga, int estado)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("actualizarEstadoVaga", true);
                $out.write_long (id_vaga);
                $out.write_long (estado);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return actualizarEstadoVaga (id_vaga, estado        );
            } finally {
                _releaseReply ($in);
            }
  } // actualizarEstadoVaga

  public com.grupo6.ParqueamentoApp.VagaDTO[] listarVagas (int id_parque)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarVagas", true);
                $out.write_long (id_parque);
                $in = _invoke ($out);
                com.grupo6.ParqueamentoApp.VagaDTO $result[] = com.grupo6.ParqueamentoApp.listaVagaDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarVagas (id_parque        );
            } finally {
                _releaseReply ($in);
            }
  } // listarVagas

  public int numeroTotalVagas (int id_parque)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("numeroTotalVagas", true);
                $out.write_long (id_parque);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return numeroTotalVagas (id_parque        );
            } finally {
                _releaseReply ($in);
            }
  } // numeroTotalVagas

  public com.grupo6.ParqueamentoApp.VagaDTO[] listarVagasDisponiveis (int id_parque)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarVagasDisponiveis", true);
                $out.write_long (id_parque);
                $in = _invoke ($out);
                com.grupo6.ParqueamentoApp.VagaDTO $result[] = com.grupo6.ParqueamentoApp.listaVagaDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarVagasDisponiveis (id_parque        );
            } finally {
                _releaseReply ($in);
            }
  } // listarVagasDisponiveis

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ParqueamentoApp/Vaga:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _VagaStub
