package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/_VagaStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Monday, 28 September 2026 18:05:55 o'clock CAT
*/

public class _VagaStub extends org.omg.CORBA.portable.ObjectImpl implements com.grupo6.ParqueamentoApp.Vaga
{


  //Definicao dos atributos da classe
  public int id_vaga ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_id_vaga", true);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return id_vaga (        );
            } finally {
                _releaseReply ($in);
            }
  } // id_vaga

  public String numero_vaga ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_numero_vaga", true);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return numero_vaga (        );
            } finally {
                _releaseReply ($in);
            }
  } // numero_vaga

  public void numero_vaga (String newNumero_vaga)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_set_numero_vaga", true);
                $out.write_string (newNumero_vaga);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                numero_vaga (newNumero_vaga        );
            } finally {
                _releaseReply ($in);
            }
  } // numero_vaga

  public int estado ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_estado", true);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return estado (        );
            } finally {
                _releaseReply ($in);
            }
  } // estado

  public void estado (int newEstado)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_set_estado", true);
                $out.write_long (newEstado);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                estado (newEstado        );
            } finally {
                _releaseReply ($in);
            }
  } // estado


  //Pode ser 0:livre ou 1:reservada
  public int id_parque ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_id_parque", true);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return id_parque (        );
            } finally {
                _releaseReply ($in);
            }
  } // id_parque


  // ==========================
  public void adicionarVaga (int id_parque, int numero_vagas)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("adicionarVaga", true);
                $out.write_long (id_parque);
                $out.write_long (numero_vagas);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                adicionarVaga (id_parque, numero_vagas        );
            } finally {
                _releaseReply ($in);
            }
  } // adicionarVaga

  public com.grupo6.ParqueamentoApp.Vaga[] listarVagas (int id_parque)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarVagas", true);
                $out.write_long (id_parque);
                $in = _invoke ($out);
                com.grupo6.ParqueamentoApp.Vaga $result[] = com.grupo6.ParqueamentoApp.VagaPackage.listaDeVagasHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarVagas (id_parque        );
            } finally {
                _releaseReply ($in);
            }
  } // listarVagas

  public com.grupo6.ParqueamentoApp.Vaga[] listarVagasDisponiveis (int id_parque)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarVagasDisponiveis", true);
                $out.write_long (id_parque);
                $in = _invoke ($out);
                com.grupo6.ParqueamentoApp.Vaga $result[] = com.grupo6.ParqueamentoApp.VagaPackage.listaDeVagasHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarVagasDisponiveis (id_parque        );
            } finally {
                _releaseReply ($in);
            }
  } // listarVagasDisponiveis

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ParqueamentoApp/Vaga:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _VagaStub
