package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/Cobertura.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 20:57:50 o'clock CAT
*/

public class Cobertura implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static com.grupo6.ParqueamentoApp.Cobertura[] __array = new com.grupo6.ParqueamentoApp.Cobertura [__size];

  public static final int _COBERTO = 0;
  public static final com.grupo6.ParqueamentoApp.Cobertura COBERTO = new com.grupo6.ParqueamentoApp.Cobertura(_COBERTO);
  public static final int _NAO_COBERTO = 1;
  public static final com.grupo6.ParqueamentoApp.Cobertura NAO_COBERTO = new com.grupo6.ParqueamentoApp.Cobertura(_NAO_COBERTO);

  public int value ()
  {
    return __value;
  }

  public static com.grupo6.ParqueamentoApp.Cobertura from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Cobertura (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Cobertura
