package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/EstadoVagaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 21:45:54 o'clock CAT
*/

abstract public class EstadoVagaHelper
{
  private static String  _id = "IDL:ParqueamentoApp/EstadoVaga:1.0";

  public static void insert (org.omg.CORBA.Any a, com.grupo6.ParqueamentoApp.EstadoVaga that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.grupo6.ParqueamentoApp.EstadoVaga extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (com.grupo6.ParqueamentoApp.EstadoVagaHelper.id (), "EstadoVaga", new String[] { "LIVRE", "OCUPADA"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.grupo6.ParqueamentoApp.EstadoVaga read (org.omg.CORBA.portable.InputStream istream)
  {
    return com.grupo6.ParqueamentoApp.EstadoVaga.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.grupo6.ParqueamentoApp.EstadoVaga value)
  {
    ostream.write_long (value.value ());
  }

}
