package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/EstadoVaga.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 20:57:50 o'clock CAT
*/

public class EstadoVaga implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static com.grupo6.ParqueamentoApp.EstadoVaga[] __array = new com.grupo6.ParqueamentoApp.EstadoVaga [__size];

  public static final int _LIVRE = 0;
  public static final com.grupo6.ParqueamentoApp.EstadoVaga LIVRE = new com.grupo6.ParqueamentoApp.EstadoVaga(_LIVRE);
  public static final int _OCUPADA = 1;
  public static final com.grupo6.ParqueamentoApp.EstadoVaga OCUPADA = new com.grupo6.ParqueamentoApp.EstadoVaga(_OCUPADA);

  public int value ()
  {
    return __value;
  }

  public static com.grupo6.ParqueamentoApp.EstadoVaga from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected EstadoVaga (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class EstadoVaga
