package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/listaParqueDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Tuesday, 6 October 2026 19:06:14 o'clock CAT
*/


//Sequencia de elementos: Sintaxe: typedef sequence<ParqueEstacionamento> ParqueEstacionamentoSeq;
public final class listaParqueDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public com.grupo6.ParqueamentoApp.ParqueDTO value[] = null;

  public listaParqueDTOHolder ()
  {
  }

  public listaParqueDTOHolder (com.grupo6.ParqueamentoApp.ParqueDTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.grupo6.ParqueamentoApp.listaParqueDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.grupo6.ParqueamentoApp.listaParqueDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.grupo6.ParqueamentoApp.listaParqueDTOHelper.type ();
  }

}
