package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/listaVagaDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Tuesday, 29 September 2026 18:56:19 o'clock CAT
*/

public final class listaVagaDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public com.grupo6.ParqueamentoApp.VagaDTO value[] = null;

  public listaVagaDTOHolder ()
  {
  }

  public listaVagaDTOHolder (com.grupo6.ParqueamentoApp.VagaDTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.grupo6.ParqueamentoApp.listaVagaDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.grupo6.ParqueamentoApp.listaVagaDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.grupo6.ParqueamentoApp.listaVagaDTOHelper.type ();
  }

}
