package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/listaReservaDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Wednesday, 7 October 2026 18:26:55 o'clock CAT
*/

public final class listaReservaDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public com.grupo6.ParqueamentoApp.ReservaDTO value[] = null;

  public listaReservaDTOHolder ()
  {
  }

  public listaReservaDTOHolder (com.grupo6.ParqueamentoApp.ReservaDTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.grupo6.ParqueamentoApp.listaReservaDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.grupo6.ParqueamentoApp.listaReservaDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.grupo6.ParqueamentoApp.listaReservaDTOHelper.type ();
  }

}
