package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/listaViaturaDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Wednesday, 7 October 2026 18:26:55 o'clock CAT
*/

public final class listaViaturaDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public com.grupo6.ParqueamentoApp.ViaturaDTO value[] = null;

  public listaViaturaDTOHolder ()
  {
  }

  public listaViaturaDTOHolder (com.grupo6.ParqueamentoApp.ViaturaDTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.grupo6.ParqueamentoApp.listaViaturaDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.grupo6.ParqueamentoApp.listaViaturaDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.grupo6.ParqueamentoApp.listaViaturaDTOHelper.type ();
  }

}
