package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/listaUsuarioDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Monday, 28 September 2026 18:05:54 o'clock CAT
*/


//Sequencia de elementos: Sintaxe: typedef sequence<ParqueEstacionamento> ParqueEstacionamentoSeq;
public final class listaUsuarioDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public com.grupo6.ParqueamentoApp.UsuarioDTO value[] = null;

  public listaUsuarioDTOHolder ()
  {
  }

  public listaUsuarioDTOHolder (com.grupo6.ParqueamentoApp.UsuarioDTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.grupo6.ParqueamentoApp.listaUsuarioDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.grupo6.ParqueamentoApp.listaUsuarioDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.grupo6.ParqueamentoApp.listaUsuarioDTOHelper.type ();
  }

}
