package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/listaUsuarioDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Monday, 28 September 2026 18:05:54 o'clock CAT
*/


//Sequencia de elementos: Sintaxe: typedef sequence<ParqueEstacionamento> ParqueEstacionamentoSeq;
abstract public class listaUsuarioDTOHelper
{
  private static String  _id = "IDL:ParqueamentoApp/listaUsuarioDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, com.grupo6.ParqueamentoApp.UsuarioDTO[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.grupo6.ParqueamentoApp.UsuarioDTO[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = com.grupo6.ParqueamentoApp.UsuarioDTOHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (com.grupo6.ParqueamentoApp.listaUsuarioDTOHelper.id (), "listaUsuarioDTO", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.grupo6.ParqueamentoApp.UsuarioDTO[] read (org.omg.CORBA.portable.InputStream istream)
  {
    com.grupo6.ParqueamentoApp.UsuarioDTO value[] = null;
    int _len0 = istream.read_long ();
    value = new com.grupo6.ParqueamentoApp.UsuarioDTO[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = com.grupo6.ParqueamentoApp.UsuarioDTOHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.grupo6.ParqueamentoApp.UsuarioDTO[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      com.grupo6.ParqueamentoApp.UsuarioDTOHelper.write (ostream, value[_i0]);
  }

}
