package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/OperacaoInvalida.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 21:45:54 o'clock CAT
*/

public final class OperacaoInvalida extends org.omg.CORBA.UserException
{
  public String mensagem = null;

  public OperacaoInvalida ()
  {
    super(OperacaoInvalidaHelper.id());
  } // ctor

  public OperacaoInvalida (String _mensagem)
  {
    super(OperacaoInvalidaHelper.id());
    mensagem = _mensagem;
  } // ctor


  public OperacaoInvalida (String $reason, String _mensagem)
  {
    super(OperacaoInvalidaHelper.id() + "  " + $reason);
    mensagem = _mensagem;
  } // ctor

} // class OperacaoInvalida
