package com.grupo6.ParqueamentoApp;

/**
* com/grupo6/ParqueamentoApp/OperacaoInvalidaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 21:45:54 o'clock CAT
*/

public final class OperacaoInvalidaHolder implements org.omg.CORBA.portable.Streamable
{
  public com.grupo6.ParqueamentoApp.OperacaoInvalida value = null;

  public OperacaoInvalidaHolder ()
  {
  }

  public OperacaoInvalidaHolder (com.grupo6.ParqueamentoApp.OperacaoInvalida initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.grupo6.ParqueamentoApp.OperacaoInvalidaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.grupo6.ParqueamentoApp.OperacaoInvalidaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.grupo6.ParqueamentoApp.OperacaoInvalidaHelper.type ();
  }

}
