package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ParqueOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Wednesday, 7 October 2026 18:26:55 o'clock CAT
*/

public interface ParqueOperations 
{

  // ==========================
  int adicionarParque (com.grupo6.ParqueamentoApp.ParqueDTO parque);
  boolean editarParque (com.grupo6.ParqueamentoApp.ParqueDTO parque);
  boolean removerParque (int id_parque);
  com.grupo6.ParqueamentoApp.ParqueDTO[] pesquisarPorCategoria (String categoria);
} // interface ParqueOperations
