package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ParqueEstacionamento.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 20:57:50 o'clock CAT
*/

public final class ParqueEstacionamento implements org.omg.CORBA.portable.IDLEntity
{
  public int id_parque = (int)0;
  public String nome = null;
  public String provincia = null;
  public String localizacao = null;
  public String telefone = null;
  public String horario = null;
  public com.grupo6.ParqueamentoApp.Cobertura cobertura = null;
  public float precoHora = (float)0;
  public String fotoUrl = null;

  public ParqueEstacionamento ()
  {
  } // ctor

  public ParqueEstacionamento (int _id_parque, String _nome, String _provincia, String _localizacao, String _telefone, String _horario, com.grupo6.ParqueamentoApp.Cobertura _cobertura, float _precoHora, String _fotoUrl)
  {
    id_parque = _id_parque;
    nome = _nome;
    provincia = _provincia;
    localizacao = _localizacao;
    telefone = _telefone;
    horario = _horario;
    cobertura = _cobertura;
    precoHora = _precoHora;
    fotoUrl = _fotoUrl;
  } // ctor

} // class ParqueEstacionamento
