package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/Parque.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Tuesday, 29 September 2026 18:56:19 o'clock CAT
*/

public interface Parque extends ParqueOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Parque
