package com.grupo6.ParqueamentoApp;

/**
* com/grupo6/ParqueamentoApp/ParqueDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Tuesday, 6 October 2026 19:06:14 o'clock CAT
*/

public final class ParqueDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public com.grupo6.ParqueamentoApp.ParqueDTO value = null;

  public ParqueDTOHolder ()
  {
  }

  public ParqueDTOHolder (com.grupo6.ParqueamentoApp.ParqueDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.grupo6.ParqueamentoApp.ParqueDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.grupo6.ParqueamentoApp.ParqueDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.grupo6.ParqueamentoApp.ParqueDTOHelper.type ();
  }

}
