package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ParqueEstacionamentoSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 21:45:54 o'clock CAT
*/


//Sequencia de elementos: Sintaxe: typedef sequence<ParqueEstacionamento> ParqueEstacionamentoSeq;
public final class ParqueEstacionamentoSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public com.grupo6.ParqueamentoApp.ParqueEstacionamento value[] = null;

  public ParqueEstacionamentoSeqHolder ()
  {
  }

  public ParqueEstacionamentoSeqHolder (com.grupo6.ParqueamentoApp.ParqueEstacionamento[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.grupo6.ParqueamentoApp.ParqueEstacionamentoSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.grupo6.ParqueamentoApp.ParqueEstacionamentoSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.grupo6.ParqueamentoApp.ParqueEstacionamentoSeqHelper.type ();
  }

}
