package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ParqueHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Monday, 28 September 2026 18:05:55 o'clock CAT
*/

abstract public class ParqueHelper
{
  private static String  _id = "IDL:ParqueamentoApp/Parque:1.0";

  public static void insert (org.omg.CORBA.Any a, com.grupo6.ParqueamentoApp.Parque that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.grupo6.ParqueamentoApp.Parque extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (com.grupo6.ParqueamentoApp.ParqueHelper.id (), "Parque");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.grupo6.ParqueamentoApp.Parque read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ParqueStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.grupo6.ParqueamentoApp.Parque value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static com.grupo6.ParqueamentoApp.Parque narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.grupo6.ParqueamentoApp.Parque)
      return (com.grupo6.ParqueamentoApp.Parque)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.grupo6.ParqueamentoApp._ParqueStub stub = new com.grupo6.ParqueamentoApp._ParqueStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static com.grupo6.ParqueamentoApp.Parque unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.grupo6.ParqueamentoApp.Parque)
      return (com.grupo6.ParqueamentoApp.Parque)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.grupo6.ParqueamentoApp._ParqueStub stub = new com.grupo6.ParqueamentoApp._ParqueStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
