package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ParquePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Tuesday, 29 September 2026 22:48:27 o'clock CAT
*/

public abstract class ParquePOA extends org.omg.PortableServer.Servant
 implements com.grupo6.ParqueamentoApp.ParqueOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("adicionarParque", new java.lang.Integer (0));
    _methods.put ("editarParque", new java.lang.Integer (1));
    _methods.put ("removerParque", new java.lang.Integer (2));
    _methods.put ("pesquisarPorCategoria", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // ==========================
       case 0:  // ParqueamentoApp/Parque/adicionarParque
       {
         com.grupo6.ParqueamentoApp.ParqueDTO parque = com.grupo6.ParqueamentoApp.ParqueDTOHelper.read (in);
         this.adicionarParque (parque);
         out = $rh.createReply();
         break;
       }

       case 1:  // ParqueamentoApp/Parque/editarParque
       {
         com.grupo6.ParqueamentoApp.ParqueDTO parque = com.grupo6.ParqueamentoApp.ParqueDTOHelper.read (in);
         boolean $result = false;
         $result = this.editarParque (parque);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // ParqueamentoApp/Parque/removerParque
       {
         int id_parque = in.read_long ();
         this.removerParque (id_parque);
         out = $rh.createReply();
         break;
       }

       case 3:  // ParqueamentoApp/Parque/pesquisarPorCategoria
       {
         String categoria = in.read_string ();
         com.grupo6.ParqueamentoApp.ParqueDTO $result[] = null;
         $result = this.pesquisarPorCategoria (categoria);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.listaParqueDTOHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ParqueamentoApp/Parque:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Parque _this() 
  {
    return ParqueHelper.narrow(
    super._this_object());
  }

  public Parque _this(org.omg.CORBA.ORB orb) 
  {
    return ParqueHelper.narrow(
    super._this_object(orb));
  }


} // class ParquePOA
