package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ParqueOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Tuesday, 6 October 2026 19:06:14 o'clock CAT
*/

public interface ParqueOperations 
{

  // ==========================
  void adicionarParque (com.grupo6.ParqueamentoApp.ParqueDTO parque);
  boolean editarParque (com.grupo6.ParqueamentoApp.ParqueDTO parque);
  void removerParque (int id_parque);
  com.grupo6.ParqueamentoApp.ParqueDTO[] pesquisarPorCategoria (String categoria);
} // interface ParqueOperations
