package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ParquePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Monday, 28 September 2026 18:05:55 o'clock CAT
*/

public abstract class ParquePOA extends org.omg.PortableServer.Servant
 implements com.grupo6.ParqueamentoApp.ParqueOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_id_parque", new java.lang.Integer (0));
    _methods.put ("_get_nome", new java.lang.Integer (1));
    _methods.put ("_set_nome", new java.lang.Integer (2));
    _methods.put ("_get_provincia", new java.lang.Integer (3));
    _methods.put ("_set_provincia", new java.lang.Integer (4));
    _methods.put ("_get_localizacao", new java.lang.Integer (5));
    _methods.put ("_set_localizacao", new java.lang.Integer (6));
    _methods.put ("_get_telefone", new java.lang.Integer (7));
    _methods.put ("_set_telefone", new java.lang.Integer (8));
    _methods.put ("_get_horario", new java.lang.Integer (9));
    _methods.put ("_set_horario", new java.lang.Integer (10));
    _methods.put ("_get_cobertura", new java.lang.Integer (11));
    _methods.put ("_set_cobertura", new java.lang.Integer (12));
    _methods.put ("_get_precoHora", new java.lang.Integer (13));
    _methods.put ("_set_precoHora", new java.lang.Integer (14));
    _methods.put ("_get_fotoUrl", new java.lang.Integer (15));
    _methods.put ("_set_fotoUrl", new java.lang.Integer (16));
    _methods.put ("adicionarParque", new java.lang.Integer (17));
    _methods.put ("editarParque", new java.lang.Integer (18));
    _methods.put ("removerParque", new java.lang.Integer (19));
    _methods.put ("listarParques", new java.lang.Integer (20));
    _methods.put ("pesquisarPorProvincia", new java.lang.Integer (21));
    _methods.put ("pesquisarPorNome", new java.lang.Integer (22));
    _methods.put ("pesquisarPorPreco", new java.lang.Integer (23));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  //Definicao dos atributos da classe
       case 0:  // ParqueamentoApp/Parque/_get_id_parque
       {
         int $result = (int)0;
         $result = this.id_parque ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // ParqueamentoApp/Parque/_get_nome
       {
         String $result = null;
         $result = this.nome ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ParqueamentoApp/Parque/_set_nome
       {
         String newNome = in.read_string ();
         this.nome (newNome);
         out = $rh.createReply();
         break;
       }

       case 3:  // ParqueamentoApp/Parque/_get_provincia
       {
         String $result = null;
         $result = this.provincia ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // ParqueamentoApp/Parque/_set_provincia
       {
         String newProvincia = in.read_string ();
         this.provincia (newProvincia);
         out = $rh.createReply();
         break;
       }

       case 5:  // ParqueamentoApp/Parque/_get_localizacao
       {
         String $result = null;
         $result = this.localizacao ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // ParqueamentoApp/Parque/_set_localizacao
       {
         String newLocalizacao = in.read_string ();
         this.localizacao (newLocalizacao);
         out = $rh.createReply();
         break;
       }

       case 7:  // ParqueamentoApp/Parque/_get_telefone
       {
         String $result = null;
         $result = this.telefone ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // ParqueamentoApp/Parque/_set_telefone
       {
         String newTelefone = in.read_string ();
         this.telefone (newTelefone);
         out = $rh.createReply();
         break;
       }

       case 9:  // ParqueamentoApp/Parque/_get_horario
       {
         String $result = null;
         $result = this.horario ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 10:  // ParqueamentoApp/Parque/_set_horario
       {
         String newHorario = in.read_string ();
         this.horario (newHorario);
         out = $rh.createReply();
         break;
       }

       case 11:  // ParqueamentoApp/Parque/_get_cobertura
       {
         String $result = null;
         $result = this.cobertura ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 12:  // ParqueamentoApp/Parque/_set_cobertura
       {
         String newCobertura = in.read_string ();
         this.cobertura (newCobertura);
         out = $rh.createReply();
         break;
       }


  //COBERTO ou NAO_COBERTO
       case 13:  // ParqueamentoApp/Parque/_get_precoHora
       {
         float $result = (float)0;
         $result = this.precoHora ();
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }


  //COBERTO ou NAO_COBERTO
       case 14:  // ParqueamentoApp/Parque/_set_precoHora
       {
         float newPrecoHora = in.read_float ();
         this.precoHora (newPrecoHora);
         out = $rh.createReply();
         break;
       }

       case 15:  // ParqueamentoApp/Parque/_get_fotoUrl
       {
         String $result = null;
         $result = this.fotoUrl ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 16:  // ParqueamentoApp/Parque/_set_fotoUrl
       {
         String newFotoUrl = in.read_string ();
         this.fotoUrl (newFotoUrl);
         out = $rh.createReply();
         break;
       }

       case 17:  // ParqueamentoApp/Parque/adicionarParque
       {
         String nome = in.read_string ();
         String provincia = in.read_string ();
         String localizacao = in.read_string ();
         String telefone = in.read_string ();
         String horario = in.read_string ();
         String cobertura = in.read_string ();
         float precoHora = in.read_float ();
         String fotoUrl = in.read_string ();
         this.adicionarParque (nome, provincia, localizacao, telefone, horario, cobertura, precoHora, fotoUrl);
         out = $rh.createReply();
         break;
       }

       case 18:  // ParqueamentoApp/Parque/editarParque
       {
         String nome = in.read_string ();
         String provincia = in.read_string ();
         String localizacao = in.read_string ();
         String telefone = in.read_string ();
         String horario = in.read_string ();
         String cobertura = in.read_string ();
         float precoHora = in.read_float ();
         String fotoUrl = in.read_string ();
         this.editarParque (nome, provincia, localizacao, telefone, horario, cobertura, precoHora, fotoUrl);
         out = $rh.createReply();
         break;
       }

       case 19:  // ParqueamentoApp/Parque/removerParque
       {
         int id_parque = in.read_long ();
         this.removerParque (id_parque);
         out = $rh.createReply();
         break;
       }

       case 20:  // ParqueamentoApp/Parque/listarParques
       {
         com.grupo6.ParqueamentoApp.Parque $result[] = null;
         $result = this.listarParques ();
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.ParquePackage.listaDeParquesHelper.write (out, $result);
         break;
       }

       case 21:  // ParqueamentoApp/Parque/pesquisarPorProvincia
       {
         String provincia = in.read_string ();
         com.grupo6.ParqueamentoApp.Parque $result[] = null;
         $result = this.pesquisarPorProvincia (provincia);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.ParquePackage.listaDeParquesHelper.write (out, $result);
         break;
       }

       case 22:  // ParqueamentoApp/Parque/pesquisarPorNome
       {
         String nome = in.read_string ();
         com.grupo6.ParqueamentoApp.Parque $result[] = null;
         $result = this.pesquisarPorNome (nome);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.ParquePackage.listaDeParquesHelper.write (out, $result);
         break;
       }

       case 23:  // ParqueamentoApp/Parque/pesquisarPorPreco
       {
         float precoMaximo = in.read_float ();
         com.grupo6.ParqueamentoApp.Parque $result[] = null;
         $result = this.pesquisarPorPreco (precoMaximo);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.ParquePackage.listaDeParquesHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ParqueamentoApp/Parque:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Parque _this() 
  {
    return ParqueHelper.narrow(
    super._this_object());
  }

  public Parque _this(org.omg.CORBA.ORB orb) 
  {
    return ParqueHelper.narrow(
    super._this_object(orb));
  }


} // class ParquePOA
