package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ParqueDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Monday, 28 September 2026 20:31:17 o'clock CAT
*/

public final class ParqueDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int id_parque = (int)0;
  public String nome = null;
  public String provincia = null;
  public String localizacao = null;
  public String telefone = null;
  public String horario = null;
  public String cobertura = null;

  //COBERTO ou NAO_COBERTO
  public float precoHora = (float)0;
  public String fotoUrl = null;

  public ParqueDTO ()
  {
  } // ctor

  public ParqueDTO (int _id_parque, String _nome, String _provincia, String _localizacao, String _telefone, String _horario, String _cobertura, float _precoHora, String _fotoUrl)
  {
    id_parque = _id_parque;
    nome = _nome;
    provincia = _provincia;
    localizacao = _localizacao;
    telefone = _telefone;
    horario = _horario;
    cobertura = _cobertura;
    precoHora = _precoHora;
    fotoUrl = _fotoUrl;
  } // ctor

} // class ParqueDTO
