package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ParqueNaoEncontrado.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 21:45:54 o'clock CAT
*/

public final class ParqueNaoEncontrado extends org.omg.CORBA.UserException
{
  public String mensagem = null;

  public ParqueNaoEncontrado ()
  {
    super(ParqueNaoEncontradoHelper.id());
  } // ctor

  public ParqueNaoEncontrado (String _mensagem)
  {
    super(ParqueNaoEncontradoHelper.id());
    mensagem = _mensagem;
  } // ctor


  public ParqueNaoEncontrado (String $reason, String _mensagem)
  {
    super(ParqueNaoEncontradoHelper.id() + "  " + $reason);
    mensagem = _mensagem;
  } // ctor

} // class ParqueNaoEncontrado
