package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ParqueDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Tuesday, 29 September 2026 22:48:27 o'clock CAT
*/

public final class ParqueDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int id_parque = (int)0;
  public String nome = null;
  public String provincia = null;
  public String localizacao = null;
  public String telefone = null;
  public String horario = null;
  public String cobertura = null;

  //COBERTO ou NAO_COBERTO
  public float preco = (float)0;
  public String foto_url = null;

  public ParqueDTO ()
  {
  } // ctor

  public ParqueDTO (int _id_parque, String _nome, String _provincia, String _localizacao, String _telefone, String _horario, String _cobertura, float _preco, String _foto_url)
  {
    id_parque = _id_parque;
    nome = _nome;
    provincia = _provincia;
    localizacao = _localizacao;
    telefone = _telefone;
    horario = _horario;
    cobertura = _cobertura;
    preco = _preco;
    foto_url = _foto_url;
  } // ctor

} // class ParqueDTO
