package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ParqueOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Sunday, 27 September 2026 19:02:25 o'clock CAT
*/

public interface ParqueOperations 
{

  //Definicao dos atributos da classe
  int id_parque ();
  String nome ();
  void nome (String newNome);
  String provincia ();
  void provincia (String newProvincia);
  String localizacao ();
  void localizacao (String newLocalizacao);
  String telefone ();
  void telefone (String newTelefone);
  String horario ();
  void horario (String newHorario);
  String cobertura ();
  void cobertura (String newCobertura);

  //COBERTO ou NAO_COBERTO
  float precoHora ();

  //COBERTO ou NAO_COBERTO
  void precoHora (float newPrecoHora);
  String fotoUrl ();
  void fotoUrl (String newFotoUrl);
  void adicionarParque (String nome, String provincia, String localizacao, String telefone, String horario, String cobertura, float precoHora, String fotoUrl);
  void editarParque (String nome, String provincia, String localizacao, String telefone, String horario, String cobertura, float precoHora, String fotoUrl);
  void removerParque (int id_parque);
  com.grupo6.ParqueamentoApp.Parque[] listarParques ();
  com.grupo6.ParqueamentoApp.Parque[] pesquisarPorProvincia (String provincia);
  com.grupo6.ParqueamentoApp.Parque[] pesquisarPorNome (String nome);
  com.grupo6.ParqueamentoApp.Parque[] pesquisarPorPreco (float precoMaximo);
} // interface ParqueOperations
