package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ReservaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Tuesday, 6 October 2026 19:06:15 o'clock CAT
*/

public interface ReservaOperations 
{

  // ==========================
  boolean criarReserva (com.grupo6.ParqueamentoApp.ReservaDTO reserva);
  com.grupo6.ParqueamentoApp.ReservaDTO obterReserva (int id_reserva);
  com.grupo6.ParqueamentoApp.ReservaDTO[] listarReservas (int id_usuario);
} // interface ReservaOperations
