package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ReservaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Tuesday, 29 September 2026 22:48:27 o'clock CAT
*/

public abstract class ReservaPOA extends org.omg.PortableServer.Servant
 implements com.grupo6.ParqueamentoApp.ReservaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("criarReserva", new java.lang.Integer (0));
    _methods.put ("obterReserva", new java.lang.Integer (1));
    _methods.put ("listarReservas", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // ==========================
       case 0:  // ParqueamentoApp/Reserva/criarReserva
       {
         com.grupo6.ParqueamentoApp.ReservaDTO reserva = com.grupo6.ParqueamentoApp.ReservaDTOHelper.read (in);
         this.criarReserva (reserva);
         out = $rh.createReply();
         break;
       }

       case 1:  // ParqueamentoApp/Reserva/obterReserva
       {
         int id_reserva = in.read_long ();
         com.grupo6.ParqueamentoApp.ReservaDTO $result = null;
         $result = this.obterReserva (id_reserva);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.ReservaDTOHelper.write (out, $result);
         break;
       }

       case 2:  // ParqueamentoApp/Reserva/listarReservas
       {
         int id_usuario = in.read_long ();
         com.grupo6.ParqueamentoApp.ReservaDTO $result[] = null;
         $result = this.listarReservas (id_usuario);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.listaReservaDTOHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ParqueamentoApp/Reserva:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Reserva _this() 
  {
    return ReservaHelper.narrow(
    super._this_object());
  }

  public Reserva _this(org.omg.CORBA.ORB orb) 
  {
    return ReservaHelper.narrow(
    super._this_object(orb));
  }


} // class ReservaPOA
