package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ReservaDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Tuesday, 6 October 2026 19:06:14 o'clock CAT
*/

public final class ReservaDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int id_reserva = (int)0;
  public String data_entrada = null;
  public String hora_entrada = null;
  public String data_saida = null;
  public String hora_saida = null;
  public float preco_total = (float)0;
  public int id_vaga = (int)0;
  public int id_usuario = (int)0;
  public int id_viatura = (int)0;

  public ReservaDTO ()
  {
  } // ctor

  public ReservaDTO (int _id_reserva, String _data_entrada, String _hora_entrada, String _data_saida, String _hora_saida, float _preco_total, int _id_vaga, int _id_usuario, int _id_viatura)
  {
    id_reserva = _id_reserva;
    data_entrada = _data_entrada;
    hora_entrada = _hora_entrada;
    data_saida = _data_saida;
    hora_saida = _hora_saida;
    preco_total = _preco_total;
    id_vaga = _id_vaga;
    id_usuario = _id_usuario;
    id_viatura = _id_viatura;
  } // ctor

} // class ReservaDTO
