package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ReservaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Monday, 28 September 2026 18:05:58 o'clock CAT
*/

public abstract class ReservaPOA extends org.omg.PortableServer.Servant
 implements com.grupo6.ParqueamentoApp.ReservaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_id_reserva", new java.lang.Integer (0));
    _methods.put ("_get_data_entrada", new java.lang.Integer (1));
    _methods.put ("_set_data_entrada", new java.lang.Integer (2));
    _methods.put ("_get_hora_entrada", new java.lang.Integer (3));
    _methods.put ("_set_hora_entrada", new java.lang.Integer (4));
    _methods.put ("_get_data_saida", new java.lang.Integer (5));
    _methods.put ("_set_data_saida", new java.lang.Integer (6));
    _methods.put ("_get_hora_saida", new java.lang.Integer (7));
    _methods.put ("_set_hora_saida", new java.lang.Integer (8));
    _methods.put ("_get_preco_total", new java.lang.Integer (9));
    _methods.put ("_get_id_vaga", new java.lang.Integer (10));
    _methods.put ("_get_id_usuario", new java.lang.Integer (11));
    _methods.put ("_get_id_viatura", new java.lang.Integer (12));
    _methods.put ("criarReserva", new java.lang.Integer (13));
    _methods.put ("obterReserva", new java.lang.Integer (14));
    _methods.put ("listarReservas", new java.lang.Integer (15));
    _methods.put ("cancelarReserva", new java.lang.Integer (16));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  //Definicao dos atributos da classe
       case 0:  // ParqueamentoApp/Reserva/_get_id_reserva
       {
         int $result = (int)0;
         $result = this.id_reserva ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // ParqueamentoApp/Reserva/_get_data_entrada
       {
         String $result = null;
         $result = this.data_entrada ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ParqueamentoApp/Reserva/_set_data_entrada
       {
         String newData_entrada = in.read_string ();
         this.data_entrada (newData_entrada);
         out = $rh.createReply();
         break;
       }

       case 3:  // ParqueamentoApp/Reserva/_get_hora_entrada
       {
         String $result = null;
         $result = this.hora_entrada ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // ParqueamentoApp/Reserva/_set_hora_entrada
       {
         String newHora_entrada = in.read_string ();
         this.hora_entrada (newHora_entrada);
         out = $rh.createReply();
         break;
       }

       case 5:  // ParqueamentoApp/Reserva/_get_data_saida
       {
         String $result = null;
         $result = this.data_saida ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // ParqueamentoApp/Reserva/_set_data_saida
       {
         String newData_saida = in.read_string ();
         this.data_saida (newData_saida);
         out = $rh.createReply();
         break;
       }

       case 7:  // ParqueamentoApp/Reserva/_get_hora_saida
       {
         String $result = null;
         $result = this.hora_saida ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // ParqueamentoApp/Reserva/_set_hora_saida
       {
         String newHora_saida = in.read_string ();
         this.hora_saida (newHora_saida);
         out = $rh.createReply();
         break;
       }

       case 9:  // ParqueamentoApp/Reserva/_get_preco_total
       {
         float $result = (float)0;
         $result = this.preco_total ();
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 10:  // ParqueamentoApp/Reserva/_get_id_vaga
       {
         int $result = (int)0;
         $result = this.id_vaga ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 11:  // ParqueamentoApp/Reserva/_get_id_usuario
       {
         int $result = (int)0;
         $result = this.id_usuario ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 12:  // ParqueamentoApp/Reserva/_get_id_viatura
       {
         int $result = (int)0;
         $result = this.id_viatura ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 13:  // ParqueamentoApp/Reserva/criarReserva
       {
         String data_entrada = in.read_string ();
         String hora_entrada = in.read_string ();
         String data_saida = in.read_string ();
         String hora_saida = in.read_string ();
         int id_vaga = in.read_long ();
         int id_usuario = in.read_long ();
         int id_viatura = in.read_long ();
         this.criarReserva (data_entrada, hora_entrada, data_saida, hora_saida, id_vaga, id_usuario, id_viatura);
         out = $rh.createReply();
         break;
       }

       case 14:  // ParqueamentoApp/Reserva/obterReserva
       {
         int id_reserva = in.read_long ();
         com.grupo6.ParqueamentoApp.Reserva $result = null;
         $result = this.obterReserva (id_reserva);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.ReservaHelper.write (out, $result);
         break;
       }

       case 15:  // ParqueamentoApp/Reserva/listarReservas
       {
         int id_usuario = in.read_long ();
         com.grupo6.ParqueamentoApp.Reserva $result[] = null;
         $result = this.listarReservas (id_usuario);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.ReservaPackage.listaDeReservasHelper.write (out, $result);
         break;
       }

       case 16:  // ParqueamentoApp/Reserva/cancelarReserva
       {
         int id_reserva = in.read_long ();
         this.cancelarReserva (id_reserva);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ParqueamentoApp/Reserva:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Reserva _this() 
  {
    return ReservaHelper.narrow(
    super._this_object());
  }

  public Reserva _this(org.omg.CORBA.ORB orb) 
  {
    return ReservaHelper.narrow(
    super._this_object(orb));
  }


} // class ReservaPOA
