package com.grupo6.ParqueamentoApp;

/**
* com/grupo6/ParqueamentoApp/ReservaDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Tuesday, 29 September 2026 22:48:27 o'clock CAT
*/

public final class ReservaDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public com.grupo6.ParqueamentoApp.ReservaDTO value = null;

  public ReservaDTOHolder ()
  {
  }

  public ReservaDTOHolder (com.grupo6.ParqueamentoApp.ReservaDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.grupo6.ParqueamentoApp.ReservaDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.grupo6.ParqueamentoApp.ReservaDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.grupo6.ParqueamentoApp.ReservaDTOHelper.type ();
  }

}
