package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ReservaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Monday, 28 September 2026 20:31:17 o'clock CAT
*/

public interface ReservaOperations 
{

  // ==========================
  void criarReserva (String data_entrada, String hora_entrada, String data_saida, String hora_saida, int id_vaga, int id_usuario, int id_viatura);
  com.grupo6.ParqueamentoApp.ReservaDTO obterReserva (int id_reserva);
  com.grupo6.ParqueamentoApp.ReservaDTO[] listarReservas (int id_usuario);
  void cancelarReserva (int id_reserva);
} // interface ReservaOperations
