package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/Reserva.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Sunday, 27 September 2026 17:57:20 o'clock CAT
*/

public interface Reserva extends ReservaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Reserva
