package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ReservaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Tuesday, 29 September 2026 22:48:27 o'clock CAT
*/

public interface ReservaOperations 
{

  // ==========================
  void criarReserva (com.grupo6.ParqueamentoApp.ReservaDTO reserva);
  com.grupo6.ParqueamentoApp.ReservaDTO obterReserva (int id_reserva);
  com.grupo6.ParqueamentoApp.ReservaDTO[] listarReservas (int id_usuario);
} // interface ReservaOperations
