package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/SistemaParqueamentoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 21:45:54 o'clock CAT
*/

public abstract class SistemaParqueamentoPOA extends org.omg.PortableServer.Servant
 implements com.grupo6.ParqueamentoApp.SistemaParqueamentoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("listarParques", new java.lang.Integer (1));
    _methods.put ("pesquisarPorProvincia", new java.lang.Integer (2));
    _methods.put ("pesquisarPorNome", new java.lang.Integer (3));
    _methods.put ("pesquisarPorPreco", new java.lang.Integer (4));
    _methods.put ("adicionarParque", new java.lang.Integer (5));
    _methods.put ("editarParque", new java.lang.Integer (6));
    _methods.put ("removerParque", new java.lang.Integer (7));
    _methods.put ("listarVagas", new java.lang.Integer (8));
    _methods.put ("listarVagasDisponiveis", new java.lang.Integer (9));
    _methods.put ("adicionarViatura", new java.lang.Integer (10));
    _methods.put ("listarViaturas", new java.lang.Integer (11));
    _methods.put ("removerViatura", new java.lang.Integer (12));
    _methods.put ("criarReserva", new java.lang.Integer (13));
    _methods.put ("obterReserva", new java.lang.Integer (14));
    _methods.put ("listarReservas", new java.lang.Integer (15));
    _methods.put ("cancelarReserva", new java.lang.Integer (16));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // ==========================
       case 0:  // ParqueamentoApp/SistemaParqueamento/login
       {
         try {
           String nome = in.read_string ();
           String senha = in.read_string ();
           com.grupo6.ParqueamentoApp.Usuario $result = null;
           $result = this.login (nome, senha);
           out = $rh.createReply();
           com.grupo6.ParqueamentoApp.UsuarioHelper.write (out, $result);
         } catch (com.grupo6.ParqueamentoApp.UsuarioNaoEncontrado $ex) {
           out = $rh.createExceptionReply ();
           com.grupo6.ParqueamentoApp.UsuarioNaoEncontradoHelper.write (out, $ex);
         }
         break;
       }


  // ==========================
       case 1:  // ParqueamentoApp/SistemaParqueamento/listarParques
       {
         com.grupo6.ParqueamentoApp.ParqueEstacionamento $result[] = null;
         $result = this.listarParques ();
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.ParqueEstacionamentoSeqHelper.write (out, $result);
         break;
       }

       case 2:  // ParqueamentoApp/SistemaParqueamento/pesquisarPorProvincia
       {
         String provincia = in.read_string ();
         com.grupo6.ParqueamentoApp.ParqueEstacionamento $result[] = null;
         $result = this.pesquisarPorProvincia (provincia);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.ParqueEstacionamentoSeqHelper.write (out, $result);
         break;
       }

       case 3:  // ParqueamentoApp/SistemaParqueamento/pesquisarPorNome
       {
         String nome = in.read_string ();
         com.grupo6.ParqueamentoApp.ParqueEstacionamento $result[] = null;
         $result = this.pesquisarPorNome (nome);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.ParqueEstacionamentoSeqHelper.write (out, $result);
         break;
       }

       case 4:  // ParqueamentoApp/SistemaParqueamento/pesquisarPorPreco
       {
         double precoMaximo = in.read_double ();
         com.grupo6.ParqueamentoApp.ParqueEstacionamento $result[] = null;
         $result = this.pesquisarPorPreco (precoMaximo);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.ParqueEstacionamentoSeqHelper.write (out, $result);
         break;
       }

       case 5:  // ParqueamentoApp/SistemaParqueamento/adicionarParque
       {
         try {
           com.grupo6.ParqueamentoApp.ParqueEstacionamento parque = com.grupo6.ParqueamentoApp.ParqueEstacionamentoHelper.read (in);
           this.adicionarParque (parque);
           out = $rh.createReply();
         } catch (com.grupo6.ParqueamentoApp.OperacaoInvalida $ex) {
           out = $rh.createExceptionReply ();
           com.grupo6.ParqueamentoApp.OperacaoInvalidaHelper.write (out, $ex);
         }
         break;
       }

       case 6:  // ParqueamentoApp/SistemaParqueamento/editarParque
       {
         try {
           com.grupo6.ParqueamentoApp.ParqueEstacionamento parque = com.grupo6.ParqueamentoApp.ParqueEstacionamentoHelper.read (in);
           this.editarParque (parque);
           out = $rh.createReply();
         } catch (com.grupo6.ParqueamentoApp.ParqueNaoEncontrado $ex) {
           out = $rh.createExceptionReply ();
           com.grupo6.ParqueamentoApp.ParqueNaoEncontradoHelper.write (out, $ex);
         } catch (com.grupo6.ParqueamentoApp.OperacaoInvalida $ex) {
           out = $rh.createExceptionReply ();
           com.grupo6.ParqueamentoApp.OperacaoInvalidaHelper.write (out, $ex);
         }
         break;
       }

       case 7:  // ParqueamentoApp/SistemaParqueamento/removerParque
       {
         try {
           int id_parque = in.read_long ();
           this.removerParque (id_parque);
           out = $rh.createReply();
         } catch (com.grupo6.ParqueamentoApp.ParqueNaoEncontrado $ex) {
           out = $rh.createExceptionReply ();
           com.grupo6.ParqueamentoApp.ParqueNaoEncontradoHelper.write (out, $ex);
         }
         break;
       }


  // ==========================
       case 8:  // ParqueamentoApp/SistemaParqueamento/listarVagas
       {
         int id_parque = in.read_long ();
         com.grupo6.ParqueamentoApp.VagaEstacionamento $result[] = null;
         $result = this.listarVagas (id_parque);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.VagaEstacionamentoSeqHelper.write (out, $result);
         break;
       }

       case 9:  // ParqueamentoApp/SistemaParqueamento/listarVagasDisponiveis
       {
         int id_parque = in.read_long ();
         com.grupo6.ParqueamentoApp.VagaEstacionamento $result[] = null;
         $result = this.listarVagasDisponiveis (id_parque);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.VagaEstacionamentoSeqHelper.write (out, $result);
         break;
       }


  // ==========================
       case 10:  // ParqueamentoApp/SistemaParqueamento/adicionarViatura
       {
         try {
           String marca = in.read_string ();
           String modelo = in.read_string ();
           String matricula = in.read_string ();
           int id_usuario = in.read_long ();
           com.grupo6.ParqueamentoApp.Viatura $result = null;
           $result = this.adicionarViatura (marca, modelo, matricula, id_usuario);
           out = $rh.createReply();
           com.grupo6.ParqueamentoApp.ViaturaHelper.write (out, $result);
         } catch (com.grupo6.ParqueamentoApp.UsuarioNaoEncontrado $ex) {
           out = $rh.createExceptionReply ();
           com.grupo6.ParqueamentoApp.UsuarioNaoEncontradoHelper.write (out, $ex);
         } catch (com.grupo6.ParqueamentoApp.OperacaoInvalida $ex) {
           out = $rh.createExceptionReply ();
           com.grupo6.ParqueamentoApp.OperacaoInvalidaHelper.write (out, $ex);
         }
         break;
       }

       case 11:  // ParqueamentoApp/SistemaParqueamento/listarViaturas
       {
         int id_usuario = in.read_long ();
         com.grupo6.ParqueamentoApp.Viatura $result[] = null;
         $result = this.listarViaturas (id_usuario);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.ViaturaSeqHelper.write (out, $result);
         break;
       }

       case 12:  // ParqueamentoApp/SistemaParqueamento/removerViatura
       {
         try {
           int id_viatura = in.read_long ();
           this.removerViatura (id_viatura);
           out = $rh.createReply();
         } catch (com.grupo6.ParqueamentoApp.ViaturaNaoEncontrada $ex) {
           out = $rh.createExceptionReply ();
           com.grupo6.ParqueamentoApp.ViaturaNaoEncontradaHelper.write (out, $ex);
         }
         break;
       }


  // ==========================
       case 13:  // ParqueamentoApp/SistemaParqueamento/criarReserva
       {
         try {
           String dataEntrada = in.read_string ();
           String horaEntrada = in.read_string ();
           String dataSaida = in.read_string ();
           String horaSaida = in.read_string ();
           float preco_total = in.read_float ();
           int idVaga = in.read_long ();
           int idUsuario = in.read_long ();
           int idViatura = in.read_long ();
           com.grupo6.ParqueamentoApp.Reserva $result = null;
           $result = this.criarReserva (dataEntrada, horaEntrada, dataSaida, horaSaida, preco_total, idVaga, idUsuario, idViatura);
           out = $rh.createReply();
           com.grupo6.ParqueamentoApp.ReservaHelper.write (out, $result);
         } catch (com.grupo6.ParqueamentoApp.UsuarioNaoEncontrado $ex) {
           out = $rh.createExceptionReply ();
           com.grupo6.ParqueamentoApp.UsuarioNaoEncontradoHelper.write (out, $ex);
         } catch (com.grupo6.ParqueamentoApp.VagaNaoEncontrada $ex) {
           out = $rh.createExceptionReply ();
           com.grupo6.ParqueamentoApp.VagaNaoEncontradaHelper.write (out, $ex);
         } catch (com.grupo6.ParqueamentoApp.ViaturaNaoEncontrada $ex) {
           out = $rh.createExceptionReply ();
           com.grupo6.ParqueamentoApp.ViaturaNaoEncontradaHelper.write (out, $ex);
         } catch (com.grupo6.ParqueamentoApp.VagaOcupada $ex) {
           out = $rh.createExceptionReply ();
           com.grupo6.ParqueamentoApp.VagaOcupadaHelper.write (out, $ex);
         } catch (com.grupo6.ParqueamentoApp.OperacaoInvalida $ex) {
           out = $rh.createExceptionReply ();
           com.grupo6.ParqueamentoApp.OperacaoInvalidaHelper.write (out, $ex);
         }
         break;
       }

       case 14:  // ParqueamentoApp/SistemaParqueamento/obterReserva
       {
         try {
           int idReserva = in.read_long ();
           com.grupo6.ParqueamentoApp.Reserva $result = null;
           $result = this.obterReserva (idReserva);
           out = $rh.createReply();
           com.grupo6.ParqueamentoApp.ReservaHelper.write (out, $result);
         } catch (com.grupo6.ParqueamentoApp.ReservaNaoEncontrada $ex) {
           out = $rh.createExceptionReply ();
           com.grupo6.ParqueamentoApp.ReservaNaoEncontradaHelper.write (out, $ex);
         }
         break;
       }

       case 15:  // ParqueamentoApp/SistemaParqueamento/listarReservas
       {
         int idUsuario = in.read_long ();
         com.grupo6.ParqueamentoApp.Reserva $result[] = null;
         $result = this.listarReservas (idUsuario);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.ReservaSeqHelper.write (out, $result);
         break;
       }

       case 16:  // ParqueamentoApp/SistemaParqueamento/cancelarReserva
       {
         try {
           int idReserva = in.read_long ();
           this.cancelarReserva (idReserva);
           out = $rh.createReply();
         } catch (com.grupo6.ParqueamentoApp.ReservaNaoEncontrada $ex) {
           out = $rh.createExceptionReply ();
           com.grupo6.ParqueamentoApp.ReservaNaoEncontradaHelper.write (out, $ex);
         } catch (com.grupo6.ParqueamentoApp.OperacaoInvalida $ex) {
           out = $rh.createExceptionReply ();
           com.grupo6.ParqueamentoApp.OperacaoInvalidaHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ParqueamentoApp/SistemaParqueamento:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public SistemaParqueamento _this() 
  {
    return SistemaParqueamentoHelper.narrow(
    super._this_object());
  }

  public SistemaParqueamento _this(org.omg.CORBA.ORB orb) 
  {
    return SistemaParqueamentoHelper.narrow(
    super._this_object(orb));
  }


} // class SistemaParqueamentoPOA
