package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/SistemaParqueamento.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 20:57:50 o'clock CAT
*/

public interface SistemaParqueamento extends SistemaParqueamentoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SistemaParqueamento
