package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/SistemaParqueamentoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 21:45:54 o'clock CAT
*/

public interface SistemaParqueamentoOperations 
{

  // ==========================
  com.grupo6.ParqueamentoApp.Usuario login (String nome, String senha) throws com.grupo6.ParqueamentoApp.UsuarioNaoEncontrado;

  // ==========================
  com.grupo6.ParqueamentoApp.ParqueEstacionamento[] listarParques ();
  com.grupo6.ParqueamentoApp.ParqueEstacionamento[] pesquisarPorProvincia (String provincia);
  com.grupo6.ParqueamentoApp.ParqueEstacionamento[] pesquisarPorNome (String nome);
  com.grupo6.ParqueamentoApp.ParqueEstacionamento[] pesquisarPorPreco (double precoMaximo);
  void adicionarParque (com.grupo6.ParqueamentoApp.ParqueEstacionamento parque) throws com.grupo6.ParqueamentoApp.OperacaoInvalida;
  void editarParque (com.grupo6.ParqueamentoApp.ParqueEstacionamento parque) throws com.grupo6.ParqueamentoApp.ParqueNaoEncontrado, com.grupo6.ParqueamentoApp.OperacaoInvalida;
  void removerParque (int id_parque) throws com.grupo6.ParqueamentoApp.ParqueNaoEncontrado;

  // ==========================
  com.grupo6.ParqueamentoApp.VagaEstacionamento[] listarVagas (int id_parque);
  com.grupo6.ParqueamentoApp.VagaEstacionamento[] listarVagasDisponiveis (int id_parque);

  // ==========================
  com.grupo6.ParqueamentoApp.Viatura adicionarViatura (String marca, String modelo, String matricula, int id_usuario) throws com.grupo6.ParqueamentoApp.UsuarioNaoEncontrado, com.grupo6.ParqueamentoApp.OperacaoInvalida;
  com.grupo6.ParqueamentoApp.Viatura[] listarViaturas (int id_usuario);
  void removerViatura (int id_viatura) throws com.grupo6.ParqueamentoApp.ViaturaNaoEncontrada;

  // ==========================
  com.grupo6.ParqueamentoApp.Reserva criarReserva (String dataEntrada, String horaEntrada, String dataSaida, String horaSaida, float preco_total, int idVaga, int idUsuario, int idViatura) throws com.grupo6.ParqueamentoApp.UsuarioNaoEncontrado, com.grupo6.ParqueamentoApp.VagaNaoEncontrada, com.grupo6.ParqueamentoApp.ViaturaNaoEncontrada, com.grupo6.ParqueamentoApp.VagaOcupada, com.grupo6.ParqueamentoApp.OperacaoInvalida;
  com.grupo6.ParqueamentoApp.Reserva obterReserva (int idReserva) throws com.grupo6.ParqueamentoApp.ReservaNaoEncontrada;
  com.grupo6.ParqueamentoApp.Reserva[] listarReservas (int idUsuario);
  void cancelarReserva (int idReserva) throws com.grupo6.ParqueamentoApp.ReservaNaoEncontrada, com.grupo6.ParqueamentoApp.OperacaoInvalida;
} // interface SistemaParqueamentoOperations
