package com.grupo6.ParqueamentoApp;

/**
* com/grupo6/ParqueamentoApp/TipoUsuarioHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 20:57:50 o'clock CAT
*/

public final class TipoUsuarioHolder implements org.omg.CORBA.portable.Streamable
{
  public com.grupo6.ParqueamentoApp.TipoUsuario value = null;

  public TipoUsuarioHolder ()
  {
  }

  public TipoUsuarioHolder (com.grupo6.ParqueamentoApp.TipoUsuario initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.grupo6.ParqueamentoApp.TipoUsuarioHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.grupo6.ParqueamentoApp.TipoUsuarioHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.grupo6.ParqueamentoApp.TipoUsuarioHelper.type ();
  }

}
