package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/TipoUsuario.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 21:45:54 o'clock CAT
*/

public class TipoUsuario implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static com.grupo6.ParqueamentoApp.TipoUsuario[] __array = new com.grupo6.ParqueamentoApp.TipoUsuario [__size];

  public static final int _COMUM = 0;
  public static final com.grupo6.ParqueamentoApp.TipoUsuario COMUM = new com.grupo6.ParqueamentoApp.TipoUsuario(_COMUM);
  public static final int _ADMIN = 1;
  public static final com.grupo6.ParqueamentoApp.TipoUsuario ADMIN = new com.grupo6.ParqueamentoApp.TipoUsuario(_ADMIN);

  public int value ()
  {
    return __value;
  }

  public static com.grupo6.ParqueamentoApp.TipoUsuario from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected TipoUsuario (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class TipoUsuario
