package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/UsuarioOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Tuesday, 29 September 2026 18:56:19 o'clock CAT
*/


//Interfaces
public interface UsuarioOperations 
{

  // ==========================
  com.grupo6.ParqueamentoApp.UsuarioDTO login (String telefone, String senha);
  void cadastrar (com.grupo6.ParqueamentoApp.UsuarioDTO usuarioDTO);
  boolean actualizarDados (com.grupo6.ParqueamentoApp.UsuarioDTO usuarioDTO);
} // interface UsuarioOperations
