package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/UsuarioOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Sunday, 27 September 2026 17:57:19 o'clock CAT
*/


//Interfaces
public interface UsuarioOperations 
{

  //Definicao dos atributos da classe
  int id_usuario ();
  String nome ();
  void nome (String newNome);
  String telefone ();
  void telefone (String newTelefone);
  String senha ();
  void senha (String newSenha);
  int tipo ();
  void tipo (int newTipo);
  com.grupo6.ParqueamentoApp.Usuario login (String nome, String senha);
  void cadastrar (String nome, String telefone, String senha, int tipo);
  com.grupo6.ParqueamentoApp.Usuario actualizarDados (String nome, String telefone, String senha);
} // interface UsuarioOperations
