package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/Usuario.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 20:57:50 o'clock CAT
*/

public final class Usuario implements org.omg.CORBA.portable.IDLEntity
{
  public int id_usuario = (int)0;
  public String nome = null;
  public String telefone = null;
  public String senha = null;
  public com.grupo6.ParqueamentoApp.TipoUsuario tipo = null;

  public Usuario ()
  {
  } // ctor

  public Usuario (int _id_usuario, String _nome, String _telefone, String _senha, com.grupo6.ParqueamentoApp.TipoUsuario _tipo)
  {
    id_usuario = _id_usuario;
    nome = _nome;
    telefone = _telefone;
    senha = _senha;
    tipo = _tipo;
  } // ctor

} // class Usuario
