package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/UsuarioPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Tuesday, 29 September 2026 18:56:19 o'clock CAT
*/


//Interfaces
public abstract class UsuarioPOA extends org.omg.PortableServer.Servant
 implements com.grupo6.ParqueamentoApp.UsuarioOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("cadastrar", new java.lang.Integer (1));
    _methods.put ("actualizarDados", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // ==========================
       case 0:  // ParqueamentoApp/Usuario/login
       {
         String telefone = in.read_string ();
         String senha = in.read_string ();
         com.grupo6.ParqueamentoApp.UsuarioDTO $result = null;
         $result = this.login (telefone, senha);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.UsuarioDTOHelper.write (out, $result);
         break;
       }

       case 1:  // ParqueamentoApp/Usuario/cadastrar
       {
         com.grupo6.ParqueamentoApp.UsuarioDTO usuarioDTO = com.grupo6.ParqueamentoApp.UsuarioDTOHelper.read (in);
         this.cadastrar (usuarioDTO);
         out = $rh.createReply();
         break;
       }

       case 2:  // ParqueamentoApp/Usuario/actualizarDados
       {
         com.grupo6.ParqueamentoApp.UsuarioDTO usuarioDTO = com.grupo6.ParqueamentoApp.UsuarioDTOHelper.read (in);
         boolean $result = false;
         $result = this.actualizarDados (usuarioDTO);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ParqueamentoApp/Usuario:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Usuario _this() 
  {
    return UsuarioHelper.narrow(
    super._this_object());
  }

  public Usuario _this(org.omg.CORBA.ORB orb) 
  {
    return UsuarioHelper.narrow(
    super._this_object(orb));
  }


} // class UsuarioPOA
