package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/UsuarioDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Monday, 28 September 2026 18:05:54 o'clock CAT
*/

public final class UsuarioDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int idUsuario = (int)0;
  public String nome = null;
  public String telefone = null;
  public int tipo = (int)0;

  public UsuarioDTO ()
  {
  } // ctor

  public UsuarioDTO (int _idUsuario, String _nome, String _telefone, int _tipo)
  {
    idUsuario = _idUsuario;
    nome = _nome;
    telefone = _telefone;
    tipo = _tipo;
  } // ctor

} // class UsuarioDTO
