package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/UsuarioOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Monday, 28 September 2026 20:31:17 o'clock CAT
*/


//Interfaces
public interface UsuarioOperations 
{

  // ==========================
  com.grupo6.ParqueamentoApp.UsuarioDTO login (String telefone, String senha);
  void cadastrar (String nome, String telefone, String senha, int tipo);
  com.grupo6.ParqueamentoApp.UsuarioDTO actualizarDados (int id_usuario, String nome, String telefone, String senha);
} // interface UsuarioOperations
