package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/UsuarioNaoEncontrado.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 20:57:50 o'clock CAT
*/

public final class UsuarioNaoEncontrado extends org.omg.CORBA.UserException
{
  public String mensagem = null;

  public UsuarioNaoEncontrado ()
  {
    super(UsuarioNaoEncontradoHelper.id());
  } // ctor

  public UsuarioNaoEncontrado (String _mensagem)
  {
    super(UsuarioNaoEncontradoHelper.id());
    mensagem = _mensagem;
  } // ctor


  public UsuarioNaoEncontrado (String $reason, String _mensagem)
  {
    super(UsuarioNaoEncontradoHelper.id() + "  " + $reason);
    mensagem = _mensagem;
  } // ctor

} // class UsuarioNaoEncontrado
