package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/UsuarioPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Sunday, 27 September 2026 17:57:19 o'clock CAT
*/


//Interfaces
public abstract class UsuarioPOA extends org.omg.PortableServer.Servant
 implements com.grupo6.ParqueamentoApp.UsuarioOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_id_usuario", new java.lang.Integer (0));
    _methods.put ("_get_nome", new java.lang.Integer (1));
    _methods.put ("_set_nome", new java.lang.Integer (2));
    _methods.put ("_get_telefone", new java.lang.Integer (3));
    _methods.put ("_set_telefone", new java.lang.Integer (4));
    _methods.put ("_get_senha", new java.lang.Integer (5));
    _methods.put ("_set_senha", new java.lang.Integer (6));
    _methods.put ("_get_tipo", new java.lang.Integer (7));
    _methods.put ("_set_tipo", new java.lang.Integer (8));
    _methods.put ("login", new java.lang.Integer (9));
    _methods.put ("cadastrar", new java.lang.Integer (10));
    _methods.put ("actualizarDados", new java.lang.Integer (11));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  //Definicao dos atributos da classe
       case 0:  // ParqueamentoApp/Usuario/_get_id_usuario
       {
         int $result = (int)0;
         $result = this.id_usuario ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // ParqueamentoApp/Usuario/_get_nome
       {
         String $result = null;
         $result = this.nome ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ParqueamentoApp/Usuario/_set_nome
       {
         String newNome = in.read_string ();
         this.nome (newNome);
         out = $rh.createReply();
         break;
       }

       case 3:  // ParqueamentoApp/Usuario/_get_telefone
       {
         String $result = null;
         $result = this.telefone ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // ParqueamentoApp/Usuario/_set_telefone
       {
         String newTelefone = in.read_string ();
         this.telefone (newTelefone);
         out = $rh.createReply();
         break;
       }

       case 5:  // ParqueamentoApp/Usuario/_get_senha
       {
         String $result = null;
         $result = this.senha ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // ParqueamentoApp/Usuario/_set_senha
       {
         String newSenha = in.read_string ();
         this.senha (newSenha);
         out = $rh.createReply();
         break;
       }

       case 7:  // ParqueamentoApp/Usuario/_get_tipo
       {
         int $result = (int)0;
         $result = this.tipo ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 8:  // ParqueamentoApp/Usuario/_set_tipo
       {
         int newTipo = in.read_long ();
         this.tipo (newTipo);
         out = $rh.createReply();
         break;
       }

       case 9:  // ParqueamentoApp/Usuario/login
       {
         String nome = in.read_string ();
         String senha = in.read_string ();
         com.grupo6.ParqueamentoApp.Usuario $result = null;
         $result = this.login (nome, senha);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.UsuarioHelper.write (out, $result);
         break;
       }

       case 10:  // ParqueamentoApp/Usuario/cadastrar
       {
         String nome = in.read_string ();
         String telefone = in.read_string ();
         String senha = in.read_string ();
         int tipo = in.read_long ();
         this.cadastrar (nome, telefone, senha, tipo);
         out = $rh.createReply();
         break;
       }

       case 11:  // ParqueamentoApp/Usuario/actualizarDados
       {
         String nome = in.read_string ();
         String telefone = in.read_string ();
         String senha = in.read_string ();
         com.grupo6.ParqueamentoApp.Usuario $result = null;
         $result = this.actualizarDados (nome, telefone, senha);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.UsuarioHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ParqueamentoApp/Usuario:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Usuario _this() 
  {
    return UsuarioHelper.narrow(
    super._this_object());
  }

  public Usuario _this(org.omg.CORBA.ORB orb) 
  {
    return UsuarioHelper.narrow(
    super._this_object(orb));
  }


} // class UsuarioPOA
