package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/UsuarioDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Tuesday, 6 October 2026 19:06:14 o'clock CAT
*/

public final class UsuarioDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int id_usuario = (int)0;
  public String nome = null;
  public String telefone = null;
  public String senha = null;
  public int tipo = (int)0;

  public UsuarioDTO ()
  {
  } // ctor

  public UsuarioDTO (int _id_usuario, String _nome, String _telefone, String _senha, int _tipo)
  {
    id_usuario = _id_usuario;
    nome = _nome;
    telefone = _telefone;
    senha = _senha;
    tipo = _tipo;
  } // ctor

} // class UsuarioDTO
