package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/VagaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Sunday, 27 September 2026 17:57:19 o'clock CAT
*/

public interface VagaOperations 
{

  //Definicao dos atributos da classe
  int id_vaga ();
  String numero_vaga ();
  void numero_vaga (String newNumero_vaga);
  int estado ();
  void estado (int newEstado);

  //Pode ser 0:livre ou 1:reservada
  int id_parque ();

  // ==========================
  void adicionarVaga (int id_parque, int numero_vagas);
  com.grupo6.ParqueamentoApp.Vaga[] listarVagas (int id_parque);
  com.grupo6.ParqueamentoApp.Vaga[] listarVagasDisponiveis (int id_parque);
} // interface VagaOperations
