package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/VagaOcupada.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 21:45:54 o'clock CAT
*/

public final class VagaOcupada extends org.omg.CORBA.UserException
{
  public String mensagem = null;

  public VagaOcupada ()
  {
    super(VagaOcupadaHelper.id());
  } // ctor

  public VagaOcupada (String _mensagem)
  {
    super(VagaOcupadaHelper.id());
    mensagem = _mensagem;
  } // ctor


  public VagaOcupada (String $reason, String _mensagem)
  {
    super(VagaOcupadaHelper.id() + "  " + $reason);
    mensagem = _mensagem;
  } // ctor

} // class VagaOcupada
