package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/VagaNaoEncontrada.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 21:45:54 o'clock CAT
*/

public final class VagaNaoEncontrada extends org.omg.CORBA.UserException
{
  public String mensagem = null;

  public VagaNaoEncontrada ()
  {
    super(VagaNaoEncontradaHelper.id());
  } // ctor

  public VagaNaoEncontrada (String _mensagem)
  {
    super(VagaNaoEncontradaHelper.id());
    mensagem = _mensagem;
  } // ctor


  public VagaNaoEncontrada (String $reason, String _mensagem)
  {
    super(VagaNaoEncontradaHelper.id() + "  " + $reason);
    mensagem = _mensagem;
  } // ctor

} // class VagaNaoEncontrada
