package com.grupo6.ParqueamentoApp;

/**
* com/grupo6/ParqueamentoApp/VagaOcupadaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 20:57:50 o'clock CAT
*/

public final class VagaOcupadaHolder implements org.omg.CORBA.portable.Streamable
{
  public com.grupo6.ParqueamentoApp.VagaOcupada value = null;

  public VagaOcupadaHolder ()
  {
  }

  public VagaOcupadaHolder (com.grupo6.ParqueamentoApp.VagaOcupada initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.grupo6.ParqueamentoApp.VagaOcupadaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.grupo6.ParqueamentoApp.VagaOcupadaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.grupo6.ParqueamentoApp.VagaOcupadaHelper.type ();
  }

}
