package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/VagaDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Tuesday, 29 September 2026 18:56:19 o'clock CAT
*/

abstract public class VagaDTOHelper
{
  private static String  _id = "IDL:ParqueamentoApp/VagaDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, com.grupo6.ParqueamentoApp.VagaDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.grupo6.ParqueamentoApp.VagaDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "id_vaga",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "numero_vaga",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "estado",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[3] = new org.omg.CORBA.StructMember (
            "id_parque",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.grupo6.ParqueamentoApp.VagaDTOHelper.id (), "VagaDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.grupo6.ParqueamentoApp.VagaDTO read (org.omg.CORBA.portable.InputStream istream)
  {
    com.grupo6.ParqueamentoApp.VagaDTO value = new com.grupo6.ParqueamentoApp.VagaDTO ();
    value.id_vaga = istream.read_long ();
    value.numero_vaga = istream.read_string ();
    value.estado = istream.read_long ();
    value.id_parque = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.grupo6.ParqueamentoApp.VagaDTO value)
  {
    ostream.write_long (value.id_vaga);
    ostream.write_string (value.numero_vaga);
    ostream.write_long (value.estado);
    ostream.write_long (value.id_parque);
  }

}
