package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/VagaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Wednesday, 7 October 2026 18:26:55 o'clock CAT
*/

public interface VagaOperations 
{

  // ==========================
  void adicionarVaga (int id_parque, int numero_de_vagas);
  boolean actualizarEstadoVaga (int id_vaga, int estado);
  com.grupo6.ParqueamentoApp.VagaDTO[] listarVagas (int id_parque);
  int numeroTotalVagas (int id_parque);
  com.grupo6.ParqueamentoApp.VagaDTO[] listarVagasDisponiveis (int id_parque);
} // interface VagaOperations
