package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/Vaga.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Monday, 28 September 2026 18:05:57 o'clock CAT
*/

public interface Vaga extends VagaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Vaga
