package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/VagaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Monday, 28 September 2026 20:31:17 o'clock CAT
*/

public abstract class VagaPOA extends org.omg.PortableServer.Servant
 implements com.grupo6.ParqueamentoApp.VagaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("adicionarVaga", new java.lang.Integer (0));
    _methods.put ("listarVagas", new java.lang.Integer (1));
    _methods.put ("numeroTotalVagas", new java.lang.Integer (2));
    _methods.put ("listarVagasDisponiveis", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // ==========================
       case 0:  // ParqueamentoApp/Vaga/adicionarVaga
       {
         int id_parque = in.read_long ();
         int numero_vagas = in.read_long ();
         this.adicionarVaga (id_parque, numero_vagas);
         out = $rh.createReply();
         break;
       }

       case 1:  // ParqueamentoApp/Vaga/listarVagas
       {
         int id_parque = in.read_long ();
         com.grupo6.ParqueamentoApp.VagaDTO $result[] = null;
         $result = this.listarVagas (id_parque);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.listaVagaDTOHelper.write (out, $result);
         break;
       }

       case 2:  // ParqueamentoApp/Vaga/numeroTotalVagas
       {
         int id_parque = in.read_long ();
         int $result = (int)0;
         $result = this.numeroTotalVagas (id_parque);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // ParqueamentoApp/Vaga/listarVagasDisponiveis
       {
         int id_parque = in.read_long ();
         com.grupo6.ParqueamentoApp.VagaDTO $result[] = null;
         $result = this.listarVagasDisponiveis (id_parque);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.listaVagaDTOHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ParqueamentoApp/Vaga:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Vaga _this() 
  {
    return VagaHelper.narrow(
    super._this_object());
  }

  public Vaga _this(org.omg.CORBA.ORB orb) 
  {
    return VagaHelper.narrow(
    super._this_object(orb));
  }


} // class VagaPOA
