package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/VagaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Monday, 28 September 2026 20:31:17 o'clock CAT
*/

public interface VagaOperations 
{

  // ==========================
  void adicionarVaga (int id_parque, int numero_vagas);
  com.grupo6.ParqueamentoApp.VagaDTO[] listarVagas (int id_parque);
  int numeroTotalVagas (int id_parque);
  com.grupo6.ParqueamentoApp.VagaDTO[] listarVagasDisponiveis (int id_parque);
} // interface VagaOperations
