package com.grupo6.ParqueamentoApp;

/**
* com/grupo6/ParqueamentoApp/VagaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Monday, 28 September 2026 18:05:56 o'clock CAT
*/

public final class VagaHolder implements org.omg.CORBA.portable.Streamable
{
  public com.grupo6.ParqueamentoApp.Vaga value = null;

  public VagaHolder ()
  {
  }

  public VagaHolder (com.grupo6.ParqueamentoApp.Vaga initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.grupo6.ParqueamentoApp.VagaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.grupo6.ParqueamentoApp.VagaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.grupo6.ParqueamentoApp.VagaHelper.type ();
  }

}
