package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/VagaEstacionamento.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 20:57:50 o'clock CAT
*/

public final class VagaEstacionamento implements org.omg.CORBA.portable.IDLEntity
{
  public int id_vaga = (int)0;
  public String numero_vaga = null;
  public com.grupo6.ParqueamentoApp.EstadoVaga estado = null;
  public int id_parque = (int)0;
  public int id_usuario = (int)0;

  public VagaEstacionamento ()
  {
  } // ctor

  public VagaEstacionamento (int _id_vaga, String _numero_vaga, com.grupo6.ParqueamentoApp.EstadoVaga _estado, int _id_parque, int _id_usuario)
  {
    id_vaga = _id_vaga;
    numero_vaga = _numero_vaga;
    estado = _estado;
    id_parque = _id_parque;
    id_usuario = _id_usuario;
  } // ctor

} // class VagaEstacionamento
