package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/VagaDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Monday, 28 September 2026 20:31:17 o'clock CAT
*/

public final class VagaDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int id_vaga = (int)0;
  public String numero_vaga = null;
  public int estado = (int)0;
  public int id_parque = (int)0;

  public VagaDTO ()
  {
  } // ctor

  public VagaDTO (int _id_vaga, String _numero_vaga, int _estado, int _id_parque)
  {
    id_vaga = _id_vaga;
    numero_vaga = _numero_vaga;
    estado = _estado;
    id_parque = _id_parque;
  } // ctor

} // class VagaDTO
