package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ViaturaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Tuesday, 29 September 2026 18:56:20 o'clock CAT
*/

public abstract class ViaturaPOA extends org.omg.PortableServer.Servant
 implements com.grupo6.ParqueamentoApp.ViaturaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("adicionarViatura", new java.lang.Integer (0));
    _methods.put ("listarViaturas", new java.lang.Integer (1));
    _methods.put ("removerViatura", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // ==========================
       case 0:  // ParqueamentoApp/Viatura/adicionarViatura
       {
         com.grupo6.ParqueamentoApp.ViaturaDTO viatura = com.grupo6.ParqueamentoApp.ViaturaDTOHelper.read (in);
         this.adicionarViatura (viatura);
         out = $rh.createReply();
         break;
       }

       case 1:  // ParqueamentoApp/Viatura/listarViaturas
       {
         int id_usuario = in.read_long ();
         com.grupo6.ParqueamentoApp.ViaturaDTO $result[] = null;
         $result = this.listarViaturas (id_usuario);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.listaViaturaDTOHelper.write (out, $result);
         break;
       }

       case 2:  // ParqueamentoApp/Viatura/removerViatura
       {
         int id_viatura = in.read_long ();
         this.removerViatura (id_viatura);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ParqueamentoApp/Viatura:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Viatura _this() 
  {
    return ViaturaHelper.narrow(
    super._this_object());
  }

  public Viatura _this(org.omg.CORBA.ORB orb) 
  {
    return ViaturaHelper.narrow(
    super._this_object(orb));
  }


} // class ViaturaPOA
