package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ViaturaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Monday, 28 September 2026 18:05:58 o'clock CAT
*/

public interface ViaturaOperations 
{

  //Definicao dos atributos da classe
  int id_viatura ();
  String marca ();
  void marca (String newMarca);
  String modelo ();
  void modelo (String newModelo);
  String matricula ();
  void matricula (String newMatricula);
  int id_usuario ();
  void adicionarViatura (String marca, String modelo, String matricula, int id_usuario);
  com.grupo6.ParqueamentoApp.Viatura[] listarViaturas (int id_usuario);
  void removerViatura (int id_viatura);
} // interface ViaturaOperations
