package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ViaturaSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 21:45:54 o'clock CAT
*/

public final class ViaturaSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public com.grupo6.ParqueamentoApp.Viatura value[] = null;

  public ViaturaSeqHolder ()
  {
  }

  public ViaturaSeqHolder (com.grupo6.ParqueamentoApp.Viatura[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.grupo6.ParqueamentoApp.ViaturaSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.grupo6.ParqueamentoApp.ViaturaSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.grupo6.ParqueamentoApp.ViaturaSeqHelper.type ();
  }

}
