package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ViaturaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Monday, 28 September 2026 20:31:17 o'clock CAT
*/

public interface ViaturaOperations 
{

  // ==========================
  void adicionarViatura (String marca, String modelo, String matricula, int id_usuario);
  com.grupo6.ParqueamentoApp.ViaturaDTO[] listarViaturas (int id_usuario);
  void removerViatura (int id_viatura);
} // interface ViaturaOperations
