package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ViaturaDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Monday, 28 September 2026 20:31:17 o'clock CAT
*/

public final class ViaturaDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int id_viatura = (int)0;
  public String marca = null;
  public String modelo = null;
  public String matricula = null;
  public int id_usuario = (int)0;

  public ViaturaDTO ()
  {
  } // ctor

  public ViaturaDTO (int _id_viatura, String _marca, String _modelo, String _matricula, int _id_usuario)
  {
    id_viatura = _id_viatura;
    marca = _marca;
    modelo = _modelo;
    matricula = _matricula;
    id_usuario = _id_usuario;
  } // ctor

} // class ViaturaDTO
