package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ViaturaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Wednesday, 7 October 2026 18:26:55 o'clock CAT
*/

public interface ViaturaOperations 
{

  // ==========================
  void adicionarViatura (com.grupo6.ParqueamentoApp.ViaturaDTO viatura);
  com.grupo6.ParqueamentoApp.ViaturaDTO[] listarViaturas (int id_usuario);
  void removerViatura (int id_viatura);
} // interface ViaturaOperations
