package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/Viatura.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Tuesday, 6 October 2026 19:06:14 o'clock CAT
*/

public interface Viatura extends ViaturaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Viatura
