package com.grupo6.ParqueamentoApp;

/**
* com/grupo6/ParqueamentoApp/ViaturaDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Tuesday, 6 October 2026 19:06:14 o'clock CAT
*/

public final class ViaturaDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public com.grupo6.ParqueamentoApp.ViaturaDTO value = null;

  public ViaturaDTOHolder ()
  {
  }

  public ViaturaDTOHolder (com.grupo6.ParqueamentoApp.ViaturaDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.grupo6.ParqueamentoApp.ViaturaDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.grupo6.ParqueamentoApp.ViaturaDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.grupo6.ParqueamentoApp.ViaturaDTOHelper.type ();
  }

}
