package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ViaturaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Sunday, 27 September 2026 17:57:19 o'clock CAT
*/

public abstract class ViaturaPOA extends org.omg.PortableServer.Servant
 implements com.grupo6.ParqueamentoApp.ViaturaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_id_viatura", new java.lang.Integer (0));
    _methods.put ("_get_marca", new java.lang.Integer (1));
    _methods.put ("_set_marca", new java.lang.Integer (2));
    _methods.put ("_get_modelo", new java.lang.Integer (3));
    _methods.put ("_set_modelo", new java.lang.Integer (4));
    _methods.put ("_get_matricula", new java.lang.Integer (5));
    _methods.put ("_set_matricula", new java.lang.Integer (6));
    _methods.put ("_get_id_usuario", new java.lang.Integer (7));
    _methods.put ("adicionarViatura", new java.lang.Integer (8));
    _methods.put ("listarViaturas", new java.lang.Integer (9));
    _methods.put ("removerViatura", new java.lang.Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  //Definicao dos atributos da classe
       case 0:  // ParqueamentoApp/Viatura/_get_id_viatura
       {
         int $result = (int)0;
         $result = this.id_viatura ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // ParqueamentoApp/Viatura/_get_marca
       {
         String $result = null;
         $result = this.marca ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ParqueamentoApp/Viatura/_set_marca
       {
         String newMarca = in.read_string ();
         this.marca (newMarca);
         out = $rh.createReply();
         break;
       }

       case 3:  // ParqueamentoApp/Viatura/_get_modelo
       {
         String $result = null;
         $result = this.modelo ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // ParqueamentoApp/Viatura/_set_modelo
       {
         String newModelo = in.read_string ();
         this.modelo (newModelo);
         out = $rh.createReply();
         break;
       }

       case 5:  // ParqueamentoApp/Viatura/_get_matricula
       {
         String $result = null;
         $result = this.matricula ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // ParqueamentoApp/Viatura/_set_matricula
       {
         String newMatricula = in.read_string ();
         this.matricula (newMatricula);
         out = $rh.createReply();
         break;
       }

       case 7:  // ParqueamentoApp/Viatura/_get_id_usuario
       {
         int $result = (int)0;
         $result = this.id_usuario ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 8:  // ParqueamentoApp/Viatura/adicionarViatura
       {
         String marca = in.read_string ();
         String modelo = in.read_string ();
         String matricula = in.read_string ();
         int id_usuario = in.read_long ();
         this.adicionarViatura (marca, modelo, matricula, id_usuario);
         out = $rh.createReply();
         break;
       }

       case 9:  // ParqueamentoApp/Viatura/listarViaturas
       {
         int id_usuario = in.read_long ();
         com.grupo6.ParqueamentoApp.Viatura $result[] = null;
         $result = this.listarViaturas (id_usuario);
         out = $rh.createReply();
         com.grupo6.ParqueamentoApp.ViaturaPackage.listaDeViaturasHelper.write (out, $result);
         break;
       }

       case 10:  // ParqueamentoApp/Viatura/removerViatura
       {
         int id_viatura = in.read_long ();
         this.removerViatura (id_viatura);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ParqueamentoApp/Viatura:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Viatura _this() 
  {
    return ViaturaHelper.narrow(
    super._this_object());
  }

  public Viatura _this(org.omg.CORBA.ORB orb) 
  {
    return ViaturaHelper.narrow(
    super._this_object(orb));
  }


} // class ViaturaPOA
