package com.grupo6.ParqueamentoApp;


/**
* com/grupo6/ParqueamentoApp/ViaturaNaoEncontrada.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Saturday, 26 September 2026 21:45:54 o'clock CAT
*/

public final class ViaturaNaoEncontrada extends org.omg.CORBA.UserException
{
  public String mensagem = null;

  public ViaturaNaoEncontrada ()
  {
    super(ViaturaNaoEncontradaHelper.id());
  } // ctor

  public ViaturaNaoEncontrada (String _mensagem)
  {
    super(ViaturaNaoEncontradaHelper.id());
    mensagem = _mensagem;
  } // ctor


  public ViaturaNaoEncontrada (String $reason, String _mensagem)
  {
    super(ViaturaNaoEncontradaHelper.id() + "  " + $reason);
    mensagem = _mensagem;
  } // ctor

} // class ViaturaNaoEncontrada
