# DO NOT EDIT THIS FILE!
#
# Python module PagamentoApp__POA generated by omniidl

import omniORB
omniORB.updateModule("PagamentoApp__POA")

# ** 1. Stub files contributing to this module
import sistema_pagamento_idl

# ** 2. Sub-modules

# ** 3. End
