package com.grupo6.ParqueamentoApp.ReservaPackage;


/**
* com/grupo6/ParqueamentoApp/ReservaPackage/listaDeReservasHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../../idl/sistema_parqueamento.idl
* Sunday, 27 September 2026 17:57:20 o'clock CAT
*/


// ==========================
public final class listaDeReservasHolder implements org.omg.CORBA.portable.Streamable
{
  public com.grupo6.ParqueamentoApp.Reserva value[] = null;

  public listaDeReservasHolder ()
  {
  }

  public listaDeReservasHolder (com.grupo6.ParqueamentoApp.Reserva[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.grupo6.ParqueamentoApp.ReservaPackage.listaDeReservasHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.grupo6.ParqueamentoApp.ReservaPackage.listaDeReservasHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.grupo6.ParqueamentoApp.ReservaPackage.listaDeReservasHelper.type ();
  }

}
