module ParqueamentoApp {



//Sequencia de elementos: Sintaxe: typedef sequence<ParqueEstacionamento> ParqueEstacionamentoSeq;




//Interfaces

    interface Usuario{
        // ==========================
        // USUÁRIO
        // ==========================

        //Definicao dos atributos da classe
        readonly attribute long id_usuario;
        attribute string nome;
        attribute string telefone;
        attribute string senha;
        attribute long tipo;


        Usuario login(
            in string telefone,
            in string senha
        );

        void cadastrar(
        in string nome,
        in string telefone,
        in string senha,
        in long tipo
        );

        Usuario actualizarDados(
        in string nome,
        in string telefone,
        in string senha  
        );

    };




    interface Parque{
        
        // ==========================
        // PARQUES
        // ==========================
        
        typedef sequence<Parque> listaDeParques;




        //Definicao dos atributos da classe
        readonly attribute long id_parque;
        attribute string nome;
        attribute string provincia;
        attribute string localizacao;
        attribute string telefone;
        attribute string horario;
        attribute string cobertura; //COBERTO ou NAO_COBERTO
        attribute float precoHora;
        attribute string fotoUrl;



        void adicionarParque(
        in string nome,
        in string provincia,
        in string localizacao,
        in string telefone,
        in string horario,
        in string cobertura, //COBERTO ou NAO_COBERTO
        in float precoHora,
        in string fotoUrl
        );


        void editarParque(
        in string nome,
        in string provincia,
        in string localizacao,
        in string telefone,
        in string horario,
        in string cobertura, //COBERTO ou NAO_COBERTO
        in float precoHora,
        in string fotoUrl
        );


        void removerParque(
            in long id_parque
        );

        listaDeParques listarParques();

        listaDeParques pesquisarPorProvincia(
            in string provincia
        );

        listaDeParques pesquisarPorNome(
            in string nome
        );

        listaDeParques pesquisarPorPreco(
            in float precoMaximo
        );


    };


    interface Vaga{

         //Definicao dos atributos da classe
        readonly attribute long id_vaga;
        attribute string numero_vaga;
        attribute long estado; //Pode ser 0:livre ou 1:reservada
        readonly attribute long id_parque;

        typedef sequence<Vaga> listaDeVagas;


        // ==========================
        // VAGAS
        // ==========================

        void adicionarVaga(
            in long id_parque,
            in long numero_vagas // O numero de vagas que queres adicionar ao parque. Por exemplo 50, 100, 200
        );

        listaDeVagas listarVagas(
            in long id_parque
        );


        listaDeVagas listarVagasDisponiveis(
            in long id_parque
        );


    };

    interface Viatura{
        //Definicao dos atributos da classe
        readonly attribute long id_viatura;
        attribute string marca;
        attribute string modelo;
        attribute string matricula;
        readonly attribute long id_usuario;

        // ==========================
        // VIATURAS
        // ==========================

        typedef sequence<Viatura> listaDeViaturas;


        void adicionarViatura(
            in string marca,
            in string modelo,
            in string matricula,
            in long id_usuario
        );


        listaDeViaturas listarViaturas(
            in long id_usuario
        );


        void removerViatura(
            in long id_viatura
        );

    };   


    interface Reserva{

    //Definicao dos atributos da classe
        readonly attribute long id_reserva;
        attribute string data_entrada;
        attribute string hora_entrada;
        attribute string data_saida;
        attribute string hora_saida;
        readonly attribute float preco_total;
        readonly attribute long id_vaga;
        readonly attribute long id_usuario;
        readonly attribute long id_viatura;


        // ==========================
        // RESERVAS
        // ==========================

    typedef sequence<Reserva> listaDeReservas;


        void criarReserva(
            in string data_entrada,
            in string hora_entrada,
            in string data_saida,
            in string hora_saida,
            in long id_vaga,
            in long id_usuario,
            in long id_viatura

        );


        Reserva obterReserva(
            in long id_reserva
        );


        listaDeReservas listarReservas(
            in long id_usuario
        );


        void cancelarReserva(
            in long id_reserva
        );

    };



};