module PagamentoApp {


    struct TransacaoDTO {
        long id_transacao;
        string tipo;
        float valor;
        string estado;
        string data;
        string hora;
        long id_conta;
    };

    struct ContaDTO {
        long id_conta;
        float saldo;
        long id_usuario;
    };

//Sequencia de elementos: Sintaxe:  sequence<ParqueEstacionamento> ParqueEstacionamentoSeq;
typedef sequence<TransacaoDTO> listaTransacaoDTO;

interface Conta{

    //Criar uma conta
    boolean criarConta(in ContaDTO conta);

    // Consultar saldo
    float consultarSaldo(
            in long id_usuario
        );

    // Buscar o Id da conta
    long buscarIDConta(
            in long id_usuario
        );

    // Depositar dinheiro
    boolean depositar(
            in long id_usuario,
            in float valor
        );

// Debitar dinheiro
    boolean debitar(
            in long id_usuario,
            in float valor
        );


};


interface Transacao {

        // Efetuar Transacao
        boolean efetuarTransacao(
            in TransacaoDTO transacao
        );

        // Listar transacoes de um usuário
        listaTransacaoDTO listarTransacoes(
            in long id_conta
        );

        // Consultar transacao
        //Transacao obterTransacao(
        //    in long id_transacao
       // ) raises (
        //    TransacaoNaoEncontrada
        //);



    };
};