module ParqueamentoApp {

    struct UsuarioDTO {
        long id_usuario;
        string nome;
        string telefone;
        string senha;
        long tipo;
    };


    struct ParqueDTO{
        long id_parque;
        string nome;
        string provincia;
        string localizacao;
        string telefone;
        string horario;
        string cobertura; //COBERTO ou NAO_COBERTO
        float preco;
        string foto_url;
    };

    struct VagaDTO {
        long id_vaga;
        string numero_vaga;
        long estado;
        long id_parque;
        };


        struct ViaturaDTO{
            long id_viatura;
            string marca;
            string modelo;
            string matricula;
            long id_usuario;
        };

    struct ReservaDTO{
        long id_reserva;
        string data_entrada;
        string hora_entrada;
        string data_saida;
        string hora_saida;
        float preco_total;
        long id_vaga;
        long id_usuario;
        long id_viatura;

    };

//Sequencia de elementos: Sintaxe: typedef sequence<ParqueEstacionamento> ParqueEstacionamentoSeq;
typedef sequence<ParqueDTO> listaParqueDTO;
typedef sequence<VagaDTO> listaVagaDTO;
typedef sequence<ViaturaDTO> listaViaturaDTO;
typedef sequence<ReservaDTO> listaReservaDTO;



//Interfaces

    interface Usuario{
        // ==========================
        // USUÁRIO
        // ==========================


        UsuarioDTO login(
            in string telefone,
            in string senha
        );

        void cadastrar (in UsuarioDTO usuarioDTO);

        boolean actualizarDados(in UsuarioDTO usuarioDTO); 

        //in id_usuario,
        //in string nome,
        //in string telefone,
        //in string senha  
       
    };




    interface Parque{
        
        // ==========================
        // PARQUES
        // ==========================

        void adicionarParque(
            in ParqueDTO parque
        );

        boolean editarParque(
            in ParqueDTO parque
        );


        void removerParque(
            in long id_parque
        );


        listaParqueDTO pesquisarPorCategoria(
            in string categoria
        ); //Categoria pode ser província, nome ou preço. 


    };


    interface Vaga{

        // ==========================
        // VAGAS
        // ==========================

        void adicionarVaga(
            in long id_parque,
            in long numero_de_vagas
        );

        listaVagaDTO listarVagas(
            in long id_parque
        );

        long numeroTotalVagas(
            in long id_parque  //Numero total de vagas num determinado parque
        );


        listaVagaDTO listarVagasDisponiveis(
            in long id_parque
        );


    };

    interface Viatura{

        // ==========================
        // VIATURAS
        // ==========================

        void adicionarViatura(
           in ViaturaDTO viatura
        );


        listaViaturaDTO listarViaturas(
            in long id_usuario
        );


        void removerViatura(
            in long id_viatura
        );

    };   


    interface Reserva{

        // ==========================
        // RESERVAS
        // ==========================

        void criarReserva(
            in ReservaDTO reserva

        );


        ReservaDTO obterReserva(
            in long id_reserva
        );


        listaReservaDTO listarReservas(
            in long id_usuario
        );


    };



};